// Package client is a Go client for aprot servers.
//
// It speaks the same JSON protocol as the generated TypeScript client, over
// a WebSocket ([Dial]) or a byte stream ([DialStream]), and needs no server
// changes. It does not import the aprot server package, so a client program
// does not inherit the server's dependencies.
//
// Most programs use a client generated by aprot's Go generator, which wraps
// this package with one typed method per handler. The generic functions here
// are the layer underneath and also work on their own, with the wire method
// name ("Group.Method") and positional params:
//
//	c, err := client.Dial(ctx, "ws://localhost:8080/ws", client.Options{})
//	if err != nil { ... }
//	defer c.Close()
//
//	user, err := client.Call[User](ctx, c, "Users.Get", []any{id})
//
// # Subscriptions
//
// [Subscribe] opens a live query. The server runs the handler, then runs it
// again whenever data it depends on changes; each result arrives on the
// subscription's channel C. Subscribe once, outside the loop, and always end
// the subscription when you stop reading it:
//
//	user := client.Subscribe[User](ctx, c, "Users.Get", []any{id})
//	defer user.Close()
//	todos := client.Subscribe[[]Todo](ctx, c, "Todos.List", nil)
//	defer todos.Close()
//
//	for {
//		select {
//		case u, ok := <-user.C:
//			if !ok {
//				return user.Err()
//			}
//			// update user
//		case t, ok := <-todos.C:
//			if !ok {
//				return todos.Err()
//			}
//			// update todos
//		case <-ctx.Done():
//			return ctx.Err()
//		}
//	}
//
// Without Close (or a cancelled ctx), a subscription outlives the function
// that made it, and the server keeps re-running its handler until the client
// closes.
//
// C holds one value, and the newest value wins: a reader that falls behind
// sees the latest result, never a backlog, and never holds up the connection.
// Every result is a full snapshot, so a skipped one loses nothing. The
// subscription survives reconnects; the fresh result after a reconnect
// arrives on the same C. An error answering the subscribe closes C, and
// [Subscription.Err] returns it; an error from a later refresh does not (see
// [OnError]).
//
// A subscription costs the server almost nothing while idle: a small entry
// in two maps, with no goroutine or timer. The cost comes when a trigger
// fires: the server re-runs the handler once for every subscription on that
// key. The server runs each subscription's first handler call in one of the
// connection's request slots (MaxConcurrentRequests, 256 by default). So
// the client keeps at most 64 subscribe frames waiting for their first
// answer, and queues the rest. Opening hundreds of subscriptions at once,
// or re-sending them all after a reconnect, never runs into that limit.
//
// [WithPatch] makes the subscription accept the partial updates the server
// sends with aprot.PatchSubscription. The client applies each patch and
// delivers the resulting full value on C.
//
// # Calls, streams and push events
//
// [Call] makes one request. While the client is reconnecting it waits for the
// connection, so bound it with a ctx deadline. A call in flight when the
// connection drops fails with [ErrConnectionLost] and is not retried, because
// the server may already have run it.
//
// [Stream] and [Stream2] call handlers that return iter.Seq or iter.Seq2, and
// yield items through a range-over-func iterator. Leaving the loop early
// cancels the handler at the server.
//
// [OnPush] registers a handler for a push event. Each handler gets its events
// in order on its own goroutine, so it may block or make calls.
//
// # Connection lifecycle
//
// [Dial] returns once the first connection is open and, with
// [Options.AuthToken], authenticated. If that fails it returns the error.
// After that the client reconnects on its own with linear backoff, using the
// intervals from the server's config frame. A server rejection (a connect
// hook error or a refused token) stops the client instead: retrying would
// only be rejected again. [Client.Done] and [Client.Err] report when and why
// the client stopped.
package client
