// Code generated by aprot. DO NOT EDIT.

// Package goclient is a typed Go client for an aprot API.
package goclient

import (
	"context"

	"github.com/marrasen/aprot/client"
)

// Client is the typed client for the API. It embeds the runtime
// client, so Close, State, Done, Err and RefreshAuth are available
// on it directly.
type Client struct {
	*client.Client
	Handlers          HandlersClient
	StreamingHandlers StreamingHandlersClient
	TasksHandler      TasksHandlerClient
}

// New wraps a connected runtime client in the typed client.
func New(c *client.Client) *Client {
	return &Client{
		Client:            c,
		Handlers:          HandlersClient{c: c},
		StreamingHandlers: StreamingHandlersClient{c: c},
		TasksHandler:      TasksHandlerClient{c: c},
	}
}

// OnRequestTaskOutputEvent calls fn for every RequestTaskOutputEvent push event.
// The returned function removes the handler.
func (c *Client) OnRequestTaskOutputEvent(fn func(RequestTaskOutputEvent)) (remove func()) {
	return client.OnPush(c.Client, "RequestTaskOutputEvent", fn)
}

// OnRequestTaskProgressEvent calls fn for every RequestTaskProgressEvent push event.
// The returned function removes the handler.
func (c *Client) OnRequestTaskProgressEvent(fn func(RequestTaskProgressEvent)) (remove func()) {
	return client.OnPush(c.Client, "RequestTaskProgressEvent", fn)
}

// OnRequestTaskTreeEvent calls fn for every RequestTaskTreeEvent push event.
// The returned function removes the handler.
func (c *Client) OnRequestTaskTreeEvent(fn func(RequestTaskTreeEvent)) (remove func()) {
	return client.OnPush(c.Client, "RequestTaskTreeEvent", fn)
}

// OnSystemNotificationEvent calls fn for every SystemNotificationEvent push event.
// The returned function removes the handler.
func (c *Client) OnSystemNotificationEvent(fn func(SystemNotificationEvent)) (remove func()) {
	return client.OnPush(c.Client, "SystemNotificationEvent", fn)
}

// OnTaskStateEvent calls fn for every TaskStateEvent push event.
// The returned function removes the handler.
func (c *Client) OnTaskStateEvent(fn func(TaskStateEvent)) (remove func()) {
	return client.OnPush(c.Client, "TaskStateEvent", fn)
}

// OnTaskUpdateEvent calls fn for every TaskUpdateEvent push event.
// The returned function removes the handler.
func (c *Client) OnTaskUpdateEvent(fn func(TaskUpdateEvent)) (remove func()) {
	return client.OnPush(c.Client, "TaskUpdateEvent", fn)
}

// OnUserCreatedEvent calls fn for every UserCreatedEvent push event.
// The returned function removes the handler.
func (c *Client) OnUserCreatedEvent(fn func(UserCreatedEvent)) (remove func()) {
	return client.OnPush(c.Client, "UserCreatedEvent", fn)
}

// OnUserUpdatedEvent calls fn for every UserUpdatedEvent push event.
// The returned function removes the handler.
func (c *Client) OnUserUpdatedEvent(fn func(UserUpdatedEvent)) (remove func()) {
	return client.OnPush(c.Client, "UserUpdatedEvent", fn)
}

// HandlersClient calls the methods of the Handlers handler group.
type HandlersClient struct {
	c *client.Client
}

// CreateUser creates a new user.
func (h HandlersClient) CreateUser(ctx context.Context, name string, email string) (*CreateUserResponse, error) {
	return client.Call[*CreateUserResponse](ctx, h.c, "Handlers.CreateUser", []any{name, email})
}

// SubscribeCreateUser runs CreateUser as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h HandlersClient) SubscribeCreateUser(ctx context.Context, name string, email string, opts ...client.SubscribeOption) *client.Subscription[*CreateUserResponse] {
	return client.Subscribe[*CreateUserResponse](ctx, h.c, "Handlers.CreateUser", []any{name, email}, opts...)
}

// GetDashboard returns a dashboard summary (no request parameter needed).
// Exercises complex type generation: map-of-struct, slice-of-pointer, map-of-slice.
func (h HandlersClient) GetDashboard(ctx context.Context) (*GetDashboardResponse, error) {
	return client.Call[*GetDashboardResponse](ctx, h.c, "Handlers.GetDashboard", nil)
}

// SubscribeGetDashboard runs GetDashboard as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h HandlersClient) SubscribeGetDashboard(ctx context.Context, opts ...client.SubscribeOption) *client.Subscription[*GetDashboardResponse] {
	return client.Subscribe[*GetDashboardResponse](ctx, h.c, "Handlers.GetDashboard", nil, opts...)
}

// GetTask retrieves a task by ID (demo: returns hardcoded task).
func (h HandlersClient) GetTask(ctx context.Context, id string) (*GetTaskResponse, error) {
	return client.Call[*GetTaskResponse](ctx, h.c, "Handlers.GetTask", []any{id})
}

// SubscribeGetTask runs GetTask as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h HandlersClient) SubscribeGetTask(ctx context.Context, id string, opts ...client.SubscribeOption) *client.Subscription[*GetTaskResponse] {
	return client.Subscribe[*GetTaskResponse](ctx, h.c, "Handlers.GetTask", []any{id}, opts...)
}

// GetUser retrieves a user by ID.
func (h HandlersClient) GetUser(ctx context.Context, id string) (*GetUserResponse, error) {
	return client.Call[*GetUserResponse](ctx, h.c, "Handlers.GetUser", []any{id})
}

// SubscribeGetUser runs GetUser as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h HandlersClient) SubscribeGetUser(ctx context.Context, id string, opts ...client.SubscribeOption) *client.Subscription[*GetUserResponse] {
	return client.Subscribe[*GetUserResponse](ctx, h.c, "Handlers.GetUser", []any{id}, opts...)
}

// ListUsers returns all users (no request parameter needed).
func (h HandlersClient) ListUsers(ctx context.Context) (*ListUsersResponse, error) {
	return client.Call[*ListUsersResponse](ctx, h.c, "Handlers.ListUsers", nil)
}

// SubscribeListUsers runs ListUsers as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h HandlersClient) SubscribeListUsers(ctx context.Context, opts ...client.SubscribeOption) *client.Subscription[*ListUsersResponse] {
	return client.Subscribe[*ListUsersResponse](ctx, h.c, "Handlers.ListUsers", nil, opts...)
}

// ProcessBatch processes items with progress reporting.
// When canceled, it distinguishes the cancel cause so the client (or an
// operator reading the logs) can tell whether the user hit Cancel, the
// connection dropped, or the server is shutting down.
func (h HandlersClient) ProcessBatch(ctx context.Context, items []string, delay int) (*ProcessBatchResponse, error) {
	return client.Call[*ProcessBatchResponse](ctx, h.c, "Handlers.ProcessBatch", []any{items, delay})
}

// SubscribeProcessBatch runs ProcessBatch as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h HandlersClient) SubscribeProcessBatch(ctx context.Context, items []string, delay int, opts ...client.SubscribeOption) *client.Subscription[*ProcessBatchResponse] {
	return client.Subscribe[*ProcessBatchResponse](ctx, h.c, "Handlers.ProcessBatch", []any{items, delay}, opts...)
}

// SendNotification sends a notification to the requesting client.
func (h HandlersClient) SendNotification(ctx context.Context, message string, level string) (*SystemNotificationEvent, error) {
	return client.Call[*SystemNotificationEvent](ctx, h.c, "Handlers.SendNotification", []any{message, level})
}

// SubscribeSendNotification runs SendNotification as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h HandlersClient) SubscribeSendNotification(ctx context.Context, message string, level string, opts ...client.SubscribeOption) *client.Subscription[*SystemNotificationEvent] {
	return client.Subscribe[*SystemNotificationEvent](ctx, h.c, "Handlers.SendNotification", []any{message, level}, opts...)
}

// StartSharedWork creates a shared task visible to all clients.
// The task auto-completes when the handler returns nil, or auto-fails on error.
// Each step runs inside tasks.SubTask so errors are captured per-step in the
// task tree. The "Lint" step always fails to demonstrate error handling.
func (h HandlersClient) StartSharedWork(ctx context.Context, title string, steps []string, delay int) (*StartSharedWorkResponse, error) {
	return client.Call[*StartSharedWorkResponse](ctx, h.c, "Handlers.StartSharedWork", []any{title, steps, delay})
}

// SubscribeStartSharedWork runs StartSharedWork as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h HandlersClient) SubscribeStartSharedWork(ctx context.Context, title string, steps []string, delay int, opts ...client.SubscribeOption) *client.Subscription[*StartSharedWorkResponse] {
	return client.Subscribe[*StartSharedWorkResponse](ctx, h.c, "Handlers.StartSharedWork", []any{title, steps, delay}, opts...)
}

// StreamingHandlersClient calls the methods of the StreamingHandlers handler group.
type StreamingHandlersClient struct {
	c *client.Client
}

// Numbers yields `count` rows with a configurable delay between each,
// simulating a slow list query (e.g. hitting multiple upstream APIs).
// The generated React hook useNumbers() accumulates items into state
// as they arrive, so the table grows row-by-row.
func (h StreamingHandlersClient) Numbers(ctx context.Context, count int, delayMs int) *client.StreamResult[*StreamRow] {
	return client.Stream[*StreamRow](ctx, h.c, "StreamingHandlers.Numbers", []any{count, delayMs})
}

// TasksHandlerClient calls the methods of the tasksHandler handler group.
type TasksHandlerClient struct {
	c *client.Client
}

// CancelTask calls the tasksHandler.CancelTask handler.
func (h TasksHandlerClient) CancelTask(ctx context.Context, taskId string) error {
	_, err := client.Call[struct{}](ctx, h.c, "tasksHandler.CancelTask", []any{taskId})
	return err
}

// ListTasks returns the current shared-task snapshot for the caller
// (IsOwner is evaluated against them). Clients hydrate from it on mount and
// reconnect: full TaskStateEvent broadcasts fire only on lifecycle changes,
// so a consumer arriving mid-task would otherwise see nothing until the next
// lifecycle event.
//
// It answers on every transport. Request-scoped callers (REST, MCP) have no
// connection, so ownership is matched on their address alone — this is how a
// caller that started a shared task over MCP polls it, since the tool result
// carries the task ID but no delivery follows it.
func (h TasksHandlerClient) ListTasks(ctx context.Context) ([]SharedTaskState, error) {
	return client.Call[[]SharedTaskState](ctx, h.c, "tasksHandler.ListTasks", nil)
}

// SubscribeListTasks runs ListTasks as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h TasksHandlerClient) SubscribeListTasks(ctx context.Context, opts ...client.SubscribeOption) *client.Subscription[[]SharedTaskState] {
	return client.Subscribe[[]SharedTaskState](ctx, h.c, "tasksHandler.ListTasks", nil, opts...)
}

// CreateUserResponse is returned after a user is successfully created.
type CreateUserResponse struct {
	// ID is the generated unique identifier for the new user.
	ID string `json:"id"`
	// Name is the display name that was stored for the user.
	Name string `json:"name"`
	// Email is the contact email address that was stored for the user.
	Email string `json:"email"`
}

// GetDashboardResponse is a demo payload exercising complex nested container types.
type GetDashboardResponse struct {
	// UsersByRole groups users by their role name.
	UsersByRole map[string][]User `json:"usersByRole"`
	// FeaturedUsers is a curated list of highlighted users.
	FeaturedUsers []*User `json:"featuredUsers"`
	// TagsByID maps numeric tag IDs to their full tag definitions.
	TagsByID map[int]Tag `json:"tagsById"`
}

// GetTaskResponse describes the current state of a background task.
type GetTaskResponse struct {
	// ID is the unique task identifier.
	ID string `json:"id"`
	// Name is a human-readable task title.
	Name string `json:"name"`
	// Status is the current lifecycle state of the task.
	Status TaskStatus `json:"status"`
}

// GetUserResponse is the payload returned when looking up a single user.
type GetUserResponse struct {
	// ID is the unique identifier of the user.
	ID string `json:"id"`
	// Name is the display name of the user.
	Name string `json:"name"`
	// Email is the contact email address of the user.
	Email string `json:"email"`
}

// ListUsersResponse is the payload returned by ListUsers.
type ListUsersResponse struct {
	// Users is the full list of known users in insertion order is not guaranteed.
	Users []User `json:"users"`
}

// ProcessBatchResponse is returned after a batch processing run completes.
type ProcessBatchResponse struct {
	// Processed is the number of items that were successfully handled.
	Processed int `json:"processed"`
	// Results contains one output entry per processed item, in input order.
	Results []string `json:"results"`
}

// RequestTaskOutputEvent is the push event sent to the requesting client with
// text output for a specific task node within a request-scoped task.
type RequestTaskOutputEvent struct {
	RequestID string `json:"requestId"`
	TaskID    string `json:"taskId"`
	Output    string `json:"output"`
}

// RequestTaskProgressEvent is the push event sent to the requesting client with
// progress for a specific task node within a request-scoped task.
type RequestTaskProgressEvent struct {
	RequestID string `json:"requestId"`
	TaskID    string `json:"taskId"`
	Current   int    `json:"current"`
	Total     int    `json:"total"`
}

// RequestTaskTreeEvent is the push event sent to the requesting client with
// a full task tree snapshot for a request-scoped task.
type RequestTaskTreeEvent struct {
	RequestID string      `json:"requestId"`
	Tasks     []*TaskNode `json:"tasks"`
}

// SharedTaskState is the wire representation of a shared task.
type SharedTaskState struct {
	ID       string         `json:"id"`
	ParentID string         `json:"parentId,omitempty"`
	Title    string         `json:"title"`
	Status   TaskNodeStatus `json:"status"`
	Error    string         `json:"error,omitempty"`
	Current  int            `json:"current,omitempty"`
	Total    int            `json:"total,omitempty"`
	Meta     *TaskMeta      `json:"meta,omitempty"`
	Children []*TaskNode    `json:"children,omitempty"`
	IsOwner  bool           `json:"isOwner"`
	// StartedHere reports that this exact connection created the task, where
	// IsOwner reports that the viewing user did. A second window of the same
	// user sees IsOwner true and StartedHere false.
	StartedHere bool `json:"startedHere"`
}

// StartSharedWorkResponse summarizes the outcome of a StartSharedWork invocation.
type StartSharedWorkResponse struct {
	// Completed is the number of steps that finished (successfully or not).
	Completed int `json:"completed"`
	// TotalSteps is the number of steps that were originally requested.
	TotalSteps int `json:"totalSteps"`
	// TotalDuration is the sum of all step durations in milliseconds.
	TotalDuration int `json:"totalDuration"`
	// Results holds one entry per executed step, in execution order.
	Results []StepResult `json:"results"`
}

// StepResult captures the outcome of a single step in a shared task run.
type StepResult struct {
	// Step is the name of the executed step.
	Step string `json:"step"`
	// Duration is the step's execution time in milliseconds.
	Duration int `json:"duration"`
	// Hash is a deterministic hash computed from the step name, for demo purposes.
	Hash string `json:"hash,omitempty"`
	// Error is the error message if the step failed; empty on success.
	Error string `json:"error,omitempty"`
}

// StreamRow is one element of the Numbers stream.
type StreamRow struct {
	Index int    `json:"index"`
	Label string `json:"label"`
	Delay int    `json:"delayMs"`
}

// SystemNotificationEvent is the wire shape of api.SystemNotificationEvent.
type SystemNotificationEvent struct {
	Message string `json:"message"`
	// info, warning, error
	Level string `json:"level"`
}

// Tag is used in GetDashboardResponse to exercise complex type collection:
// map values, slice-of-pointer, and map-of-slice scenarios.
type Tag struct {
	// ID is the unique identifier of the tag.
	ID string `json:"id"`
	// Name is the human-readable label of the tag.
	Name string `json:"name"`
	// Color is a CSS color string used to render the tag in the UI.
	Color string `json:"color"`
}

// TaskMeta is user-provided metadata attached to a shared task.
type TaskMeta struct {
	// UserName is the display name of the user who initiated the task.
	UserName string `json:"userName,omitempty"`
}

// TaskNode is the JSON-serializable snapshot of a task sent to the client.
type TaskNode struct {
	ID       string         `json:"id"`
	Title    string         `json:"title"`
	Status   TaskNodeStatus `json:"status"`
	Error    string         `json:"error,omitempty"`
	Current  int            `json:"current,omitempty"`
	Total    int            `json:"total,omitempty"`
	Meta     *TaskMeta      `json:"meta,omitempty"`
	Children []*TaskNode    `json:"children,omitempty"`
}

// TaskNodeStatus represents the current state of a task node.
type TaskNodeStatus string

const (
	TaskNodeStatusCreated   TaskNodeStatus = "created"
	TaskNodeStatusRunning   TaskNodeStatus = "running"
	TaskNodeStatusCompleted TaskNodeStatus = "completed"
	TaskNodeStatusFailed    TaskNodeStatus = "failed"
)

// TaskStateEvent is the push event broadcast to all clients when shared tasks change.
type TaskStateEvent struct {
	Tasks []SharedTaskState `json:"tasks"`
}

// TaskStatus represents the status of a task.
type TaskStatus string

const (
	TaskStatusCreated   TaskStatus = "created"
	TaskStatusRunning   TaskStatus = "running"
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusFailed    TaskStatus = "failed"
)

// TaskUpdateEvent is the push event for per-node output and progress updates
// on shared tasks.
type TaskUpdateEvent struct {
	TaskID  string  `json:"taskId"`
	Output  *string `json:"output,omitempty"`
	Current *int    `json:"current,omitempty"`
	Total   *int    `json:"total,omitempty"`
}

// User represents a registered user in the demo application.
type User struct {
	// ID is the unique identifier of the user.
	ID string `json:"id"`
	// Name is the display name of the user.
	Name string `json:"name"`
	// Email is the contact email address of the user.
	Email string `json:"email"`
}

// UserCreatedEvent is the wire shape of api.UserCreatedEvent.
type UserCreatedEvent struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

// UserUpdatedEvent is the wire shape of api.UserUpdatedEvent.
type UserUpdatedEvent struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
