// Code generated by aprot. DO NOT EDIT.

// Package goclienttest is a typed Go client for an aprot API.
package goclienttest

import (
	"context"
	"encoding/json/jsontext"
	"time"

	"github.com/marrasen/aprot/client"
	"github.com/marrasen/aprot/internal/gentestpkg"
)

// Client is the typed client for the API. It embeds the runtime
// client, so Close, State, Done, Err and RefreshAuth are available
// on it directly.
type Client struct {
	*client.Client
	Admin AdminClient
	Items ItemsClient
}

// New wraps a connected runtime client in the typed client.
func New(c *client.Client) *Client {
	return &Client{
		Client: c,
		Admin:  AdminClient{c: c},
		Items:  ItemsClient{c: c},
	}
}

// OnItemAdded calls fn for every ItemAdded push event.
// The returned function removes the handler.
func (c *Client) OnItemAdded(fn func(ItemAdded)) (remove func()) {
	return client.OnPush(c.Client, "ItemAdded", fn)
}

// AdminClient calls the methods of the Admin handler group.
type AdminClient struct {
	c *client.Client
}

// Ping answers with pong.
func (h AdminClient) Ping(ctx context.Context) (string, error) {
	return client.Call[string](ctx, h.c, "Admin.Ping", nil)
}

// SubscribePing runs Ping as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h AdminClient) SubscribePing(ctx context.Context, opts ...client.SubscribeOption[string]) *client.Subscription[string] {
	return client.Subscribe[string](ctx, h.c, "Admin.Ping", nil, opts...)
}

// ItemsClient calls the methods of the Items handler group.
type ItemsClient struct {
	c *client.Client
}

// Add stores an item, refreshes List subscriptions and pushes ItemAdded.
func (h ItemsClient) Add(ctx context.Context, item GogentestItem) error {
	_, err := client.Call[struct{}](ctx, h.c, "Items.Add", []any{item})
	return err
}

// Download returns a binary result.
func (h ItemsClient) Download(ctx context.Context, name string) (*client.Blob, error) {
	return client.Call[*client.Blob](ctx, h.c, "Items.Download", []any{name})
}

// SubscribeDownload runs Download as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h ItemsClient) SubscribeDownload(ctx context.Context, name string, opts ...client.SubscribeOption[*client.Blob]) *client.Subscription[*client.Blob] {
	return client.Subscribe[*client.Blob](ctx, h.c, "Items.Download", []any{name}, opts...)
}

// Echo returns its argument, so every field travels both ways.
func (h ItemsClient) Echo(ctx context.Context, item GogentestItem) (GogentestItem, error) {
	return client.Call[GogentestItem](ctx, h.c, "Items.Echo", []any{item})
}

// SubscribeEcho runs Echo as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h ItemsClient) SubscribeEcho(ctx context.Context, item GogentestItem, opts ...client.SubscribeOption[GogentestItem]) *client.Subscription[GogentestItem] {
	return client.Subscribe[GogentestItem](ctx, h.c, "Items.Echo", []any{item}, opts...)
}

// Export streams n rows.
func (h ItemsClient) Export(ctx context.Context, n int) *client.StreamResult[*Row] {
	return client.Stream[*Row](ctx, h.c, "Items.Export", []any{n})
}

// Get returns one item. A zero id returns nil without an error.
func (h ItemsClient) Get(ctx context.Context, id int) (*GogentestItem, error) {
	return client.Call[*GogentestItem](ctx, h.c, "Items.Get", []any{id})
}

// SubscribeGet runs Get as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h ItemsClient) SubscribeGet(ctx context.Context, id int, opts ...client.SubscribeOption[*GogentestItem]) *client.Subscription[*GogentestItem] {
	return client.Subscribe[*GogentestItem](ctx, h.c, "Items.Get", []any{id}, opts...)
}

// List returns the items with the given status.
func (h ItemsClient) List(ctx context.Context, status Status) ([]GogentestItem, error) {
	return client.Call[[]GogentestItem](ctx, h.c, "Items.List", []any{status})
}

// SubscribeList runs List as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h ItemsClient) SubscribeList(ctx context.Context, status Status, opts ...client.SubscribeOption[[]GogentestItem]) *client.Subscription[[]GogentestItem] {
	return client.Subscribe[[]GogentestItem](ctx, h.c, "Items.List", []any{status}, opts...)
}

// Pairs streams key/value pairs.
func (h ItemsClient) Pairs(ctx context.Context) *client.Stream2Result[string, int] {
	return client.Stream2[string, int](ctx, h.c, "Items.Pairs", nil)
}

// Sum adds its variadic arguments.
func (h ItemsClient) Sum(ctx context.Context, base int, nums ...int) (int, error) {
	params := []any{base}
	for _, x := range nums {
		params = append(params, x)
	}
	return client.Call[int](ctx, h.c, "Items.Sum", params)
}

// SubscribeSum runs Sum as a live query.
// Each result arrives on the subscription's C; close it with Close.
func (h ItemsClient) SubscribeSum(ctx context.Context, base int, nums []int, opts ...client.SubscribeOption[int]) *client.Subscription[int] {
	params := []any{base}
	for _, x := range nums {
		params = append(params, x)
	}
	return client.Subscribe[int](ctx, h.c, "Items.Sum", params, opts...)
}

// Custom error codes registered on the server. Test an error for one
// with client.HasCode(err, ErrCode...).
const (
	ErrCodeNotFound = 1000
)

// Base is embedded into Item; its fields are inlined on the wire.
type Base struct {
	ID        int       `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
}

// Extra is embedded by pointer.
type Extra struct {
	Note string `json:"note,omitempty"`
}

// GogentestItem exercises every mapping rule of the Go generator.
type GogentestItem struct {
	Base
	*Extra
	Inner
	// Name is the display name.
	Name     string                    `json:"name"`
	Tags     []string                  `json:"tags,omitempty"`
	Status   Status                    `json:"status"`
	Priority Priority                  `json:"priority"`
	Price    string                    `json:"price"`
	Score    jsontext.Value            `json:"score"`
	Code     string                    `json:"code"`
	Note     *string                   `json:"nullNote"`
	Count    *int64                    `json:"count"`
	When     *time.Time                `json:"when"`
	Gen      *int                      `json:"gen"`
	Timeout  time.Duration             `json:"timeout"`
	Interval time.Duration             `json:"interval,format:units"`
	Raw      jsontext.Value            `json:"raw,omitempty"`
	Attrs    map[string]any            `json:"attrs"`
	Matrix   [2][2]int                 `json:"matrix"`
	Bytes    []byte                    `json:"bytes"`
	Named    RawBytes                  `json:"named"`
	Parent   *GogentestItem            `json:"parent,omitempty"`
	Children map[string]*GogentestItem `json:"children,omitempty"`
	Anon     struct {
		X int
	} `json:"anon"`
	Big      int64            `json:"big,string"`
	Opt      *string          `json:"opt,omitzero"`
	Payload  *Payload         `json:"payload"`
	File     client.Blob      `json:"file"`
	Other    OtherItem        `json:"other"`
	Color    gentestpkg.Color `json:"color"`
	ByStatus map[Status]int   `json:"byStatus"`
	Untagged string
}

// Inner is an unexported embedded struct; json/v2 still inlines its fields.
type Inner struct {
	Secret string `json:"secret"`
}

// ItemAdded is pushed when an item is added.
type ItemAdded struct {
	ID int `json:"id"`
}

// OtherItem is the wire shape of other.Item.
type OtherItem struct {
	Label string `json:"label"`
}

// Payload is the codegen override for Item.Payload.
type Payload struct {
	Kind string `json:"kind"`
}

// Priority is an int enum named through fmt.Stringer.
type Priority int

const (
	PriorityLow  Priority = 0
	PriorityHigh Priority = 1
)

// RawBytes is a named byte slice, which json/v2 encodes as a number array.
type RawBytes []byte

// Row is a stream item.
type Row struct {
	N int `json:"n"`
}

// Status is a string enum.
type Status string

const (
	StatusPending    Status = "pending"
	StatusDone       Status = "done"
	StatusInProgress Status = "in-progress"
)
