version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST*"
        - "-SA1019"
  exclusions:
    presets:
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - errcheck
