package aprot

import (
	"fmt"
	"sort"
	"strings"
)

// SourceDocs is godoc metadata for handlers and their parameter/response
// types: method doc comments, parameter names, struct and field docs. At
// development time aprot extracts it from source with go/ast on demand — but
// a deployed binary has no source on disk, so runtime consumers of this data
// (OpenAPI generation, REST path-parameter names, MCP tool and schema
// descriptions) would silently come up empty. [GenerateSourceDocsGo] emits a
// Go file that bakes the extracted docs into the build; the emitted
// RegisterSourceDocs function hands them to [Registry.SetSourceDocs].
type SourceDocs struct {
	// Handlers is keyed by receiver struct name, then method name.
	Handlers map[string]map[string]HandlerDoc
	// Types is keyed by struct type name.
	Types map[string]TypeDoc
}

// HandlerDoc is the per-method documentation baked by GenerateSourceDocsGo.
type HandlerDoc struct {
	ParamNames []string // parameter names, excluding the leading context.Context
	Doc        string   // godoc above the method declaration
}

// TypeDoc is the per-struct documentation baked by GenerateSourceDocsGo.
type TypeDoc struct {
	Doc       string            // godoc above the type declaration
	FieldDocs map[string]string // Go field name → godoc
}

// SetSourceDocs seeds the registry with baked documentation. Once set, it is
// used instead of parsing Go source from disk wherever aprot needs godoc at
// runtime: OpenAPI summaries/descriptions, REST path-parameter names, schema
// descriptions from [Registry.SchemaFor], and MCP tool descriptions.
// Typically called from the file emitted by [GenerateSourceDocsGo] rather
// than written by hand.
func (r *Registry) SetSourceDocs(docs *SourceDocs) {
	if docs == nil {
		r.sourceDocs = nil
		return
	}
	m := &sourceMeta{
		Handlers: make(map[string]map[string]handlerMeta),
		Types:    make(map[string]typeMeta),
	}
	for structName, methods := range docs.Handlers {
		mm := make(map[string]handlerMeta, len(methods))
		for name, h := range methods {
			mm[name] = handlerMeta(h)
		}
		m.Handlers[structName] = mm
	}
	for typeName, t := range docs.Types {
		m.Types[typeName] = typeMeta(t)
	}
	r.sourceDocs = m
}

// resolveSourceMeta returns the registry's documentation metadata: the baked
// docs installed via SetSourceDocs when present, otherwise a fresh AST
// extraction from the registered handler groups' source directories (which
// yields empty metadata when the source is not on disk, e.g. in a deployed
// binary).
func (r *Registry) resolveSourceMeta() *sourceMeta {
	if r.sourceDocs != nil {
		return r.sourceDocs
	}
	dirs := make(map[string]bool)
	for _, group := range r.groups {
		if dir := group.SourceDir(); dir != "" {
			dirs[dir] = true
		}
	}
	return extractSourceMeta(dirs)
}

// GenerateSourceDocsGo extracts godoc metadata from the registered handler
// groups' source directories and emits a Go file (package goPackage) that
// bakes it into the build:
//
//	// Code generated by aprot. DO NOT EDIT.
//	package api
//	func RegisterSourceDocs(r *aprot.Registry) { … }
//
// Call the emitted RegisterSourceDocs right after building the registry.
// Commit the file and regenerate it alongside the TypeScript clients, so CI
// can catch drift the same way (#312). Must run where the handler source is
// on disk — the same environment the client generators run in. Output is
// deterministic for a given source tree.
func GenerateSourceDocsGo(registry *Registry, goPackage string) ([]byte, error) {
	if goPackage == "" {
		return nil, fmt.Errorf("aprot: GenerateSourceDocsGo requires a package name")
	}
	dirs := make(map[string]bool)
	for _, group := range registry.Groups() {
		if dir := group.SourceDir(); dir != "" {
			dirs[dir] = true
		}
	}
	meta := extractSourceMeta(dirs)

	var b strings.Builder
	b.WriteString("// Code generated by aprot. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", goPackage)
	b.WriteString("import \"github.com/marrasen/aprot\"\n\n")
	b.WriteString("// RegisterSourceDocs seeds r with handler and type documentation extracted\n")
	b.WriteString("// from source at generation time, so OpenAPI descriptions, REST parameter\n")
	b.WriteString("// names and MCP tool descriptions work in deployed binaries without source.\n")
	b.WriteString("func RegisterSourceDocs(r *aprot.Registry) {\n")
	b.WriteString("\tr.SetSourceDocs(&aprot.SourceDocs{\n")

	b.WriteString("\t\tHandlers: map[string]map[string]aprot.HandlerDoc{\n")
	for _, structName := range sortedKeys(meta.Handlers) {
		fmt.Fprintf(&b, "\t\t\t%q: {\n", structName)
		methods := meta.Handlers[structName]
		for _, methodName := range sortedKeys(methods) {
			h := methods[methodName]
			fmt.Fprintf(&b, "\t\t\t\t%q: {ParamNames: %s, Doc: %q},\n",
				methodName, goStringSlice(h.ParamNames), h.Doc)
		}
		b.WriteString("\t\t\t},\n")
	}
	b.WriteString("\t\t},\n")

	b.WriteString("\t\tTypes: map[string]aprot.TypeDoc{\n")
	for _, typeName := range sortedKeys(meta.Types) {
		t := meta.Types[typeName]
		fmt.Fprintf(&b, "\t\t\t%q: {Doc: %q, FieldDocs: map[string]string{\n", typeName, t.Doc)
		for _, fieldName := range sortedKeys(t.FieldDocs) {
			fmt.Fprintf(&b, "\t\t\t\t%q: %q,\n", fieldName, t.FieldDocs[fieldName])
		}
		b.WriteString("\t\t\t}},\n")
	}
	b.WriteString("\t\t},\n")

	b.WriteString("\t})\n")
	b.WriteString("}\n")
	return []byte(b.String()), nil
}

// goStringSlice renders a []string as Go source, nil-safe.
func goStringSlice(ss []string) string {
	if len(ss) == 0 {
		return "nil"
	}
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

// sortedKeys returns the sorted keys of a string-keyed map.
func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
