// Code generated by aprot. DO NOT EDIT.
// Handler: Handlers
import { useCallback } from 'react';
import { ApiClient, useQuery, useMutation, usePushEvent } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
    UseMutationOptions,
    UseMutationResult,
    PushHandler,
    UsePushResult,
} from './client';

export const TaskStatus = {
    Created: "created",
    Running: "running",
    Completed: "completed",
    Failed: "failed",
} as const;
export type TaskStatusType = typeof TaskStatus[keyof typeof TaskStatus];

export interface CreateUserResponse {
    id: string;
    name: string;
    email: string;
}

export interface GetDashboardResponse {
    usersByRole: Record<string, User[]>;
    featuredUsers: User[];
    tagsById: Record<number, Tag>;
}

export interface GetTaskResponse {
    id: string;
    name: string;
    status: TaskStatusType;
}

export interface GetUserResponse {
    id: string;
    name: string;
    email: string;
}

export interface ListUsersResponse {
    users: User[];
}

export interface ProcessBatchResponse {
    processed: number;
    results: string[];
}

export interface StartSharedWorkResponse {
    completed: number;
    totalSteps: number;
    totalDuration: number;
    results: StepResult[];
}

export interface StepResult {
    step: string;
    duration: number;
    hash?: string;
    error?: string;
}

export interface SystemNotificationEvent {
    message: string;
    level: string;
}

export interface Tag {
    id: string;
    name: string;
    color: string;
}

export interface User {
    id: string;
    name: string;
    email: string;
}

export interface UserCreatedEvent {
    id: string;
    name: string;
    email: string;
}

export interface UserUpdatedEvent {
    id: string;
    name: string;
    email: string;
}


export function createUser(client: ApiClient, name: string, email: string, options?: RequestOptions): Promise<CreateUserResponse> {
    return client.request<CreateUserResponse>('Handlers.CreateUser', [name, email], options);
}

export function subscribeCreateUser(client: ApiClient, name: string, email: string, callback: (data: CreateUserResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<CreateUserResponse>('Handlers.CreateUser', [name, email], callback, onError);
}


export function getDashboard(client: ApiClient, options?: RequestOptions): Promise<GetDashboardResponse> {
    return client.request<GetDashboardResponse>('Handlers.GetDashboard', [], options);
}

export function subscribeGetDashboard(client: ApiClient, callback: (data: GetDashboardResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<GetDashboardResponse>('Handlers.GetDashboard', [], callback, onError);
}


export function getTask(client: ApiClient, id: string, options?: RequestOptions): Promise<GetTaskResponse> {
    return client.request<GetTaskResponse>('Handlers.GetTask', [id], options);
}

export function subscribeGetTask(client: ApiClient, id: string, callback: (data: GetTaskResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<GetTaskResponse>('Handlers.GetTask', [id], callback, onError);
}


export function getUser(client: ApiClient, id: string, options?: RequestOptions): Promise<GetUserResponse> {
    return client.request<GetUserResponse>('Handlers.GetUser', [id], options);
}

export function subscribeGetUser(client: ApiClient, id: string, callback: (data: GetUserResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<GetUserResponse>('Handlers.GetUser', [id], callback, onError);
}


export function listUsers(client: ApiClient, options?: RequestOptions): Promise<ListUsersResponse> {
    return client.request<ListUsersResponse>('Handlers.ListUsers', [], options);
}

export function subscribeListUsers(client: ApiClient, callback: (data: ListUsersResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<ListUsersResponse>('Handlers.ListUsers', [], callback, onError);
}


export function processBatch(client: ApiClient, items: string[], delay: number, options?: RequestOptions): Promise<ProcessBatchResponse> {
    return client.request<ProcessBatchResponse>('Handlers.ProcessBatch', [items, delay], options);
}

export function subscribeProcessBatch(client: ApiClient, items: string[], delay: number, callback: (data: ProcessBatchResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<ProcessBatchResponse>('Handlers.ProcessBatch', [items, delay], callback, onError);
}


export function sendNotification(client: ApiClient, message: string, level: string, options?: RequestOptions): Promise<SystemNotificationEvent> {
    return client.request<SystemNotificationEvent>('Handlers.SendNotification', [message, level], options);
}

export function subscribeSendNotification(client: ApiClient, message: string, level: string, callback: (data: SystemNotificationEvent) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<SystemNotificationEvent>('Handlers.SendNotification', [message, level], callback, onError);
}


export function startSharedWork(client: ApiClient, title: string, steps: string[], delay: number, options?: RequestOptions): Promise<StartSharedWorkResponse> {
    return client.request<StartSharedWorkResponse>('Handlers.StartSharedWork', [title, steps, delay], options);
}

export function subscribeStartSharedWork(client: ApiClient, title: string, steps: string[], delay: number, callback: (data: StartSharedWorkResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<StartSharedWorkResponse>('Handlers.StartSharedWork', [title, steps, delay], callback, onError);
}

export function onUserCreatedEvent(client: ApiClient, handler: PushHandler<UserCreatedEvent>): () => void {
    return client.onPush<UserCreatedEvent>('UserCreatedEvent', handler);
}

export function onUserUpdatedEvent(client: ApiClient, handler: PushHandler<UserUpdatedEvent>): () => void {
    return client.onPush<UserUpdatedEvent>('UserUpdatedEvent', handler);
}

export function onSystemNotificationEvent(client: ApiClient, handler: PushHandler<SystemNotificationEvent>): () => void {
    return client.onPush<SystemNotificationEvent>('SystemNotificationEvent', handler);
}

// React Hooks for Handlers

/**
 * Subscribes to `Handlers.CreateUser` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details.
 */
export function useCreateUser(name: string, email: string, options?: UseQueryOptions): UseQueryResult<CreateUserResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, name: string, email: string) => createUser(client, name, email, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [name, email], _subscribe: { method: 'Handlers.CreateUser', params: [name, email] } });
}

/**
 * Imperative mutation hook for `Handlers.CreateUser`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useCreateUserMutation(options?: UseMutationOptions): UseMutationResult<[name: string, email: string], CreateUserResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, name: string, email: string) => createUser(client, name, email, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

/**
 * Subscribes to `Handlers.GetDashboard` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details.
 */
export function useGetDashboard(options?: UseQueryOptions): UseQueryResult<GetDashboardResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => getDashboard(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'Handlers.GetDashboard', params: [] } });
}

/**
 * Imperative mutation hook for `Handlers.GetDashboard`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useGetDashboardMutation(options?: UseMutationOptions): UseMutationResult<[], GetDashboardResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => getDashboard(client, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

/**
 * Subscribes to `Handlers.GetTask` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details.
 */
export function useGetTask(id: string, options?: UseQueryOptions): UseQueryResult<GetTaskResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => getTask(client, id, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id], _subscribe: { method: 'Handlers.GetTask', params: [id] } });
}

/**
 * Imperative mutation hook for `Handlers.GetTask`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useGetTaskMutation(options?: UseMutationOptions): UseMutationResult<[id: string], GetTaskResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => getTask(client, id, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

/**
 * Subscribes to `Handlers.GetUser` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details.
 */
export function useGetUser(id: string, options?: UseQueryOptions): UseQueryResult<GetUserResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => getUser(client, id, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id], _subscribe: { method: 'Handlers.GetUser', params: [id] } });
}

/**
 * Imperative mutation hook for `Handlers.GetUser`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useGetUserMutation(options?: UseMutationOptions): UseMutationResult<[id: string], GetUserResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => getUser(client, id, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

/**
 * Subscribes to `Handlers.ListUsers` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details.
 */
export function useListUsers(options?: UseQueryOptions): UseQueryResult<ListUsersResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => listUsers(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'Handlers.ListUsers', params: [] } });
}

/**
 * Imperative mutation hook for `Handlers.ListUsers`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useListUsersMutation(options?: UseMutationOptions): UseMutationResult<[], ListUsersResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => listUsers(client, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

/**
 * Subscribes to `Handlers.ProcessBatch` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details.
 */
export function useProcessBatch(items: string[], delay: number, options?: UseQueryOptions): UseQueryResult<ProcessBatchResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, items: string[], delay: number) => processBatch(client, items, delay, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [items, delay], _subscribe: { method: 'Handlers.ProcessBatch', params: [items, delay] } });
}

/**
 * Imperative mutation hook for `Handlers.ProcessBatch`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useProcessBatchMutation(options?: UseMutationOptions): UseMutationResult<[items: string[], delay: number], ProcessBatchResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, items: string[], delay: number) => processBatch(client, items, delay, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

/**
 * Subscribes to `Handlers.SendNotification` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details.
 */
export function useSendNotification(message: string, level: string, options?: UseQueryOptions): UseQueryResult<SystemNotificationEvent> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, message: string, level: string) => sendNotification(client, message, level, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [message, level], _subscribe: { method: 'Handlers.SendNotification', params: [message, level] } });
}

/**
 * Imperative mutation hook for `Handlers.SendNotification`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useSendNotificationMutation(options?: UseMutationOptions): UseMutationResult<[message: string, level: string], SystemNotificationEvent> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, message: string, level: string) => sendNotification(client, message, level, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

/**
 * Subscribes to `Handlers.StartSharedWork` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details.
 */
export function useStartSharedWork(title: string, steps: string[], delay: number, options?: UseQueryOptions): UseQueryResult<StartSharedWorkResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, title: string, steps: string[], delay: number) => startSharedWork(client, title, steps, delay, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [title, steps, delay], _subscribe: { method: 'Handlers.StartSharedWork', params: [title, steps, delay] } });
}

/**
 * Imperative mutation hook for `Handlers.StartSharedWork`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useStartSharedWorkMutation(options?: UseMutationOptions): UseMutationResult<[title: string, steps: string[], delay: number], StartSharedWorkResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, title: string, steps: string[], delay: number) => startSharedWork(client, title, steps, delay, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

export function useUserCreatedEvent(options?: { maxEvents?: number }): UsePushResult<UserCreatedEvent> {
    return usePushEvent(onUserCreatedEvent, options);
}

export function useUserUpdatedEvent(options?: { maxEvents?: number }): UsePushResult<UserUpdatedEvent> {
    return usePushEvent(onUserUpdatedEvent, options);
}

export function useSystemNotificationEvent(options?: { maxEvents?: number }): UsePushResult<SystemNotificationEvent> {
    return usePushEvent(onSystemNotificationEvent, options);
}
