// Code generated by aprot. DO NOT EDIT.
// Handler: StreamingHandlers
import { useCallback } from 'react';
import { ApiClient, useStream } from './client';
import type {
    RequestOptions,
    UseStreamOptions,
    UseStreamResult,
} from './client';

export interface StreamRow {
    index: number;
    label: string;
    delayMs: number;
}


export function numbers(client: ApiClient, count: number, delayMs: number, options?: RequestOptions): AsyncIterable<StreamRow> {
    return client.requestStream<StreamRow>('StreamingHandlers.Numbers', [count, delayMs], options);
}

// React Hooks for StreamingHandlers

/**
 * Streams items from `StreamingHandlers.Numbers` and accumulates them into `items`.
 * The stream restarts when parameters change and cleans up on unmount.
 * See {@link UseStreamResult} for return value details.
 */
export function useNumbers(count: number, delayMs: number, options?: UseStreamOptions): UseStreamResult<StreamRow> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, count: number, delayMs: number) => numbers(client, count, delayMs, { signal }),
        [],
    );
    return useStream(wrappedFn, { ...(options ?? {}), params: [count, delayMs] as [number, number] });
}
