// Code generated by aprot. DO NOT EDIT.
// Handler: Todos
import { useCallback } from 'react';
import { ApiClient, useQuery, useMutation } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
    UseMutationOptions,
    UseMutationResult,
} from './client';

export interface CreateTodoRequest {
    title: string;
    description: string;
    priority: number;
}

export interface ListTodosResponse {
    todos: Todo[];
    total: number;
}

export interface Todo {
    id: string;
    title: string;
    description: string;
    priority: number;
    done: boolean;
}

export interface UpdateTodoRequest {
    title?: string;
    description?: string;
    priority?: number;
    done?: boolean;
}

export function createTodo(client: ApiClient, req: CreateTodoRequest, options?: RequestOptions): Promise<Todo> {
    return client.request<Todo>('Todos.CreateTodo', [req], options);
}

export function subscribeCreateTodo(client: ApiClient, req: CreateTodoRequest, callback: (data: Todo) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<Todo>('Todos.CreateTodo', [req], callback, onError);
}

export function deleteTodo(client: ApiClient, id: string, options?: RequestOptions): Promise<void> {
    return client.request<void>('Todos.DeleteTodo', [id], options);
}

export function subscribeDeleteTodo(client: ApiClient, id: string, callback: (data: void) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<void>('Todos.DeleteTodo', [id], callback, onError);
}

export function getTodo(client: ApiClient, id: string, options?: RequestOptions): Promise<Todo> {
    return client.request<Todo>('Todos.GetTodo', [id], options);
}

export function subscribeGetTodo(client: ApiClient, id: string, callback: (data: Todo) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<Todo>('Todos.GetTodo', [id], callback, onError);
}

export function listTodos(client: ApiClient, options?: RequestOptions): Promise<ListTodosResponse> {
    return client.request<ListTodosResponse>('Todos.ListTodos', [], options);
}

export function subscribeListTodos(client: ApiClient, callback: (data: ListTodosResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<ListTodosResponse>('Todos.ListTodos', [], callback, onError);
}

export function updateTodo(client: ApiClient, id: string, req: UpdateTodoRequest, options?: RequestOptions): Promise<Todo> {
    return client.request<Todo>('Todos.UpdateTodo', [id, req], options);
}

export function subscribeUpdateTodo(client: ApiClient, id: string, req: UpdateTodoRequest, callback: (data: Todo) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<Todo>('Todos.UpdateTodo', [id, req], callback, onError);
}

// React Hooks for Todos

/**
 * Subscribes to `Todos.CreateTodo` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details.
 */
export function useCreateTodo(req: CreateTodoRequest, options?: UseQueryOptions): UseQueryResult<Todo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, req: CreateTodoRequest) => createTodo(client, req, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [req], _subscribe: { method: 'Todos.CreateTodo', params: [req] } });
}

/**
 * Imperative mutation hook for `Todos.CreateTodo`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useCreateTodoMutation(options?: UseMutationOptions): UseMutationResult<[req: CreateTodoRequest], Todo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, req: CreateTodoRequest) => createTodo(client, req, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

/**
 * Subscribes to `Todos.DeleteTodo` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details.
 */
export function useDeleteTodo(id: string, options?: UseQueryOptions): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => deleteTodo(client, id, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id], _subscribe: { method: 'Todos.DeleteTodo', params: [id] } });
}

/**
 * Imperative mutation hook for `Todos.DeleteTodo`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useDeleteTodoMutation(options?: UseMutationOptions): UseMutationResult<[id: string], void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => deleteTodo(client, id, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

/**
 * Subscribes to `Todos.GetTodo` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details.
 */
export function useGetTodo(id: string, options?: UseQueryOptions): UseQueryResult<Todo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => getTodo(client, id, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id], _subscribe: { method: 'Todos.GetTodo', params: [id] } });
}

/**
 * Imperative mutation hook for `Todos.GetTodo`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useGetTodoMutation(options?: UseMutationOptions): UseMutationResult<[id: string], Todo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => getTodo(client, id, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

/**
 * Subscribes to `Todos.ListTodos` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details.
 */
export function useListTodos(options?: UseQueryOptions): UseQueryResult<ListTodosResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => listTodos(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'Todos.ListTodos', params: [] } });
}

/**
 * Imperative mutation hook for `Todos.ListTodos`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useListTodosMutation(options?: UseMutationOptions): UseMutationResult<[], ListTodosResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => listTodos(client, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}

/**
 * Subscribes to `Todos.UpdateTodo` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details.
 */
export function useUpdateTodo(id: string, req: UpdateTodoRequest, options?: UseQueryOptions): UseQueryResult<Todo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string, req: UpdateTodoRequest) => updateTodo(client, id, req, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id, req], _subscribe: { method: 'Todos.UpdateTodo', params: [id, req] } });
}

/**
 * Imperative mutation hook for `Todos.UpdateTodo`. Nothing happens until
 * you call `mutate()`. See {@link UseMutationResult} for return value details.
 */
export function useUpdateTodoMutation(options?: UseMutationOptions): UseMutationResult<[id: string, req: UpdateTodoRequest], Todo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string, req: UpdateTodoRequest) => updateTodo(client, id, req, { signal, onProgress: options?.onProgress }),
        [options?.onProgress],
    );
    return useMutation(wrappedFn);
}
