// Code generated by aprot. DO NOT EDIT.
// Handler: Todos
import { useCallback } from 'react';
import { ApiClient, useQuery } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
} from './client';

export interface CreateTodoRequest {
    title: string;
    description: string;
    priority: number;
}

export interface ListTodosResponse {
    todos: Todo[];
    total: number;
}

export interface Todo {
    id: string;
    title: string;
    description: string;
    priority: number;
    done: boolean;
}

export interface UpdateTodoRequest {
    title?: string;
    description?: string;
    priority?: number;
    done?: boolean;
}


export function createTodo(client: ApiClient, req: CreateTodoRequest, options?: RequestOptions): Promise<Todo> {
    return client.request<Todo>('Todos.CreateTodo', [req], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
createTodo.method = 'Todos.CreateTodo' as const;

export function subscribeCreateTodo(client: ApiClient, req: CreateTodoRequest, callback: (data: Todo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Todo>('Todos.CreateTodo', [req], callback, onError, options);
}


export function deleteTodo(client: ApiClient, id: string, options?: RequestOptions): Promise<void> {
    return client.request<void>('Todos.DeleteTodo', [id], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
deleteTodo.method = 'Todos.DeleteTodo' as const;

export function subscribeDeleteTodo(client: ApiClient, id: string, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Todos.DeleteTodo', [id], callback, onError, options);
}


export function getTodo(client: ApiClient, id: string, options?: RequestOptions): Promise<Todo> {
    return client.request<Todo>('Todos.GetTodo', [id], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
getTodo.method = 'Todos.GetTodo' as const;

export function subscribeGetTodo(client: ApiClient, id: string, callback: (data: Todo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Todo>('Todos.GetTodo', [id], callback, onError, options);
}


export function listTodos(client: ApiClient, options?: RequestOptions): Promise<ListTodosResponse> {
    return client.request<ListTodosResponse>('Todos.ListTodos', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
listTodos.method = 'Todos.ListTodos' as const;

export function subscribeListTodos(client: ApiClient, callback: (data: ListTodosResponse) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<ListTodosResponse>('Todos.ListTodos', [], callback, onError, options);
}


export function updateTodo(client: ApiClient, id: string, req: UpdateTodoRequest, options?: RequestOptions): Promise<Todo> {
    return client.request<Todo>('Todos.UpdateTodo', [id, req], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
updateTodo.method = 'Todos.UpdateTodo' as const;

export function subscribeUpdateTodo(client: ApiClient, id: string, req: UpdateTodoRequest, callback: (data: Todo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Todo>('Todos.UpdateTodo', [id, req], callback, onError, options);
}

// React Hooks for Todos

/**
 * Subscribes to `Todos.CreateTodo` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useCreateTodo(req: CreateTodoRequest, options?: UseQueryOptions<Todo>): UseQueryResult<Todo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, req: CreateTodoRequest) => createTodo(client, req, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [req], _subscribe: { method: 'Todos.CreateTodo', params: [req] } });
}

/**
 * Subscribes to `Todos.DeleteTodo` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useDeleteTodo(id: string, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => deleteTodo(client, id, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id], _subscribe: { method: 'Todos.DeleteTodo', params: [id] } });
}

/**
 * Subscribes to `Todos.GetTodo` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useGetTodo(id: string, options?: UseQueryOptions<Todo>): UseQueryResult<Todo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => getTodo(client, id, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id], _subscribe: { method: 'Todos.GetTodo', params: [id] } });
}

/**
 * Subscribes to `Todos.ListTodos` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useListTodos(options?: UseQueryOptions<ListTodosResponse>): UseQueryResult<ListTodosResponse> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => listTodos(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'Todos.ListTodos', params: [] } });
}

/**
 * Subscribes to `Todos.UpdateTodo` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useUpdateTodo(id: string, req: UpdateTodoRequest, options?: UseQueryOptions<Todo>): UseQueryResult<Todo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string, req: UpdateTodoRequest) => updateTodo(client, id, req, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id, req], _subscribe: { method: 'Todos.UpdateTodo', params: [id, req] } });
}
