// Code generated by aprot. DO NOT EDIT.


// Standard error codes
export const ErrorCode = {
    ParseError: -32700,
    InvalidRequest: -32600,
    MethodNotFound: -32601,
    InvalidParams: -32602,
    InternalError: -32603,
    ValidationFailed: -32604,
    Canceled: -32800,
    Unauthorized: -32001,
    ConnectionRejected: -32002,
    Forbidden: -32003,
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];



// FieldError is one entry in the structured payload that the server returns
// alongside CodeValidationFailed (-32604) responses. The shape mirrors the Go
// FieldError struct in validate.go on the server side.
export interface FieldError {
    field: string;
    tag: string;
    value: unknown;
    param: string;
    message: string;
}

// ApiError is thrown when the server returns an error response
export class ApiError extends Error {
    readonly code: number;
    // data is the structured payload the server attached to the error, if any.
    // For CodeValidationFailed responses this is FieldError[]; for other codes
    // it may be undefined or carry a code-specific shape. Use getValidationErrors
    // to safely extract field-level validation failures.
    readonly data?: unknown;

    constructor(code: number, message: string, data?: unknown) {
        super(message);
        this.name = 'ApiError';
        this.code = code;
        this.data = data;
    }

    // Helper methods for checking error types
    isUnauthorized(): boolean { return this.code === ErrorCode.Unauthorized; }
    isForbidden(): boolean { return this.code === ErrorCode.Forbidden; }
    isNotFound(): boolean { return this.code === ErrorCode.MethodNotFound; }
    isInvalidParams(): boolean { return this.code === ErrorCode.InvalidParams; }
    isValidationFailed(): boolean { return this.code === ErrorCode.ValidationFailed; }
    isCanceled(): boolean { return this.code === ErrorCode.Canceled; }
    isConnectionRejected(): boolean { return this.code === ErrorCode.ConnectionRejected; }
}

// getValidationErrors returns the structured FieldError list when err is a
// validation failure (code -32604), or null otherwise. Use this instead of
// hand-rolling the instanceof + code check + Array.isArray + cast pattern.
export function getValidationErrors(err: unknown): FieldError[] | null {
    if (!(err instanceof ApiError)) return null;
    if (err.code !== ErrorCode.ValidationFailed) return null;
    if (!Array.isArray(err.data)) return null;
    return err.data as FieldError[];
}

// ConnectionErrorReason classifies why a connection failed or could not be
// used. Browsers deliberately collapse most pre-WebSocket-upgrade failures
// (DNS, TCP refused, TLS handshake, HTTP 4xx during upgrade) into close
// code 1006 with no diagnostic text, so finer-grained classification is
// not achievable from JS — these all surface as 'network-error'.
//
//   - 'offline':         navigator.onLine was false at failure time.
//   - 'server-rejected': server sent an ApiError with code ConnectionRejected
//                        (e.g. invalid session) before closing. The original
//                        ApiError is attached via ConnectionError.cause.
//   - 'server-closed':   transport closed cleanly after the WebSocket upgrade
//                        completed; closeCode and closeReason are populated.
//   - 'network-error':   pre-upgrade failure or close code 1006 — refused,
//                        unreachable, TLS or upgrade-time HTTP error.
//   - 'manual':          the caller invoked client.disconnect().
export type ConnectionErrorReason =
    | 'offline'
    | 'server-rejected'
    | 'server-closed'
    | 'network-error'
    | 'manual';

// ConnectionErrorInit carries the optional diagnostic fields attached to a
// ConnectionError. closeCode/closeReason mirror the WebSocket CloseEvent
// fields when available; cause carries the underlying ApiError for
// 'server-rejected' so callers can read err.cause.code / err.cause.data.
export interface ConnectionErrorInit {
    closeCode?: number;
    closeReason?: string;
    cause?: unknown;
}

// ConnectionError is thrown (or attached to a rejected promise) whenever a
// request fails because the connection itself is unhealthy — distinct from
// ApiError, which represents a structured server-side error response. It
// extends Error so existing `catch (err) { ... }` blocks keep working; new
// code can switch on err.reason for user-facing messaging.
export class ConnectionError extends Error {
    readonly reason: ConnectionErrorReason;
    readonly closeCode?: number;
    readonly closeReason?: string;
    // cause is the underlying ApiError for 'server-rejected', if any.
    // For other reasons it is undefined. Typed `unknown` to align with the
    // ES2022 Error.cause convention without forcing a specific shape.
    readonly cause?: unknown;

    constructor(reason: ConnectionErrorReason, message: string, init?: ConnectionErrorInit) {
        super(message);
        this.name = 'ConnectionError';
        this.reason = reason;
        this.closeCode = init?.closeCode;
        this.closeReason = init?.closeReason;
        this.cause = init?.cause;
    }

    isOffline(): boolean { return this.reason === 'offline'; }
    isServerRejected(): boolean { return this.reason === 'server-rejected'; }
    isServerClosed(): boolean { return this.reason === 'server-closed'; }
    isNetworkError(): boolean { return this.reason === 'network-error'; }
    isManual(): boolean { return this.reason === 'manual'; }
}



export interface RequestOptions {
    signal?: AbortSignal;
    onProgress?: (current: number, total: number, message: string) => void;
    onMessage?: (msg: Record<string, unknown>) => void;
    /** @internal Called with the allocated request ID before the request is sent. */
    _onStart?: (requestId: string) => void;
    /** @internal Called when the request settles (response, error, or cancel). */
    _onSettle?: () => void;
}

export type PushHandler<T> = (data: T) => void;

export type ConnectionState = 'disconnected' | 'connecting' | 'connected' | 'reconnecting';

export interface ApiClientOptions {
    /** Transport type. Default: 'websocket' */
    transport?: 'websocket' | 'sse';
    /** Enable auto-reconnect on connection loss. Default: true */
    reconnect?: boolean;
    /** Initial reconnect delay in ms. Default: 1000 */
    reconnectInterval?: number;
    /** Maximum reconnect delay in ms (for exponential backoff). Default: 30000 */
    reconnectMaxInterval?: number;
    /** Maximum reconnect attempts. 0 = unlimited. Default: 0 */
    reconnectMaxAttempts?: number;
    /** Called when the server rejects the connection (e.g. invalid session). Connection will not auto-reconnect. */
    onConnectionRejected?: (error: ApiError) => void;
}

type ResolvedOptions = Required<Omit<ApiClientOptions, 'onConnectionRejected'>> & Pick<ApiClientOptions, 'onConnectionRejected'>;

const defaultOptions: ResolvedOptions = {
    transport: 'websocket',
    reconnect: true,
    reconnectInterval: 1000,
    reconnectMaxInterval: 30000,
    reconnectMaxAttempts: 0,
};



/**
 * Returns a WebSocket URL based on the current page location.
 * Automatically uses wss: for https: pages and ws: for http: pages.
 * @param path - The WebSocket endpoint path (default: '/ws')
 */
export function getWebSocketUrl(path: string = '/ws'): string {
    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    return `${protocol}//${window.location.host}${path}`;
}

/**
 * Returns an SSE base URL based on the current page location.
 * @param path - The SSE endpoint base path (default: '/sse')
 */
export function getSSEUrl(path: string = '/sse'): string {
    return `${window.location.protocol}//${window.location.host}${path}`;
}



// TransportCloseInfo carries WebSocket CloseEvent diagnostics from the
// transport up to the client's classification logic. SSE has no equivalent
// (the EventSource error event exposes nothing structured), so the SSE
// transport synthesizes an empty info object — it lands as 'network-error'
// after offline/manual checks, which is the most accurate bucket browsers
// will let us name.
interface TransportCloseInfo {
    /** WebSocket CloseEvent.code, when available. 1006 = abnormal (pre-upgrade) closure. */
    code?: number;
    /** WebSocket CloseEvent.reason, when non-empty. */
    reason?: string;
    /** WebSocket CloseEvent.wasClean — true only if a close handshake completed. */
    wasClean?: boolean;
    /** True when the close was already classified as a server-rejected protocol error. */
    serverRejected?: boolean;
}

// Internal transport interface
interface ClientTransport {
    connect(url: string, onMessage: (data: string) => void, onClose: (info?: TransportCloseInfo) => void): Promise<void>;
    send(message: object): void;
    disconnect(): void;
    isConnected(): boolean;
}

class WebSocketTransport implements ClientTransport {
    private ws: WebSocket | null = null;

    connect(url: string, onMessage: (data: string) => void, onClose: (info?: TransportCloseInfo) => void): Promise<void> {
        return new Promise((resolve, reject) => {
            // Detach and close previous socket so its deferred onclose
            // cannot interfere with the new connection (mobile wake race).
            if (this.ws) {
                this.ws.onclose = null;
                this.ws.onerror = null;
                this.ws.onmessage = null;
                this.ws.close();
                this.ws = null;
            }
            let opened = false;
            this.ws = new WebSocket(url);
            this.ws.onopen = () => { opened = true; resolve(); };
            this.ws.onerror = () => {}; // Error is followed by close
            this.ws.onmessage = (e) => onMessage(e.data);
            this.ws.onclose = (event) => {
                this.ws = null;
                // Surface the structured CloseEvent so the ApiClient can
                // distinguish a clean post-upgrade close (codes 1000-1015,
                // 4xxx) from a pre-upgrade abnormal closure (1006). The
                // browser deliberately hides upgrade-time HTTP status for
                // fingerprinting reasons, so 1006 is as fine-grained as
                // we get for refused/DNS/TLS/4xx-during-upgrade failures.
                const info: TransportCloseInfo = {
                    code: event.code,
                    reason: event.reason || undefined,
                    wasClean: event.wasClean,
                };
                if (!opened) reject(new Error('WebSocket closed before open'));
                onClose(info);
            };
        });
    }

    send(message: object): void {
        this.ws?.send(JSON.stringify(message));
    }

    disconnect(): void {
        this.ws?.close();
        this.ws = null;
    }

    isConnected(): boolean {
        return this.ws !== null && this.ws.readyState === WebSocket.OPEN;
    }
}

type ClientMessage =
    | { type: 'request'; id: string; method: string; params: unknown[] }
    | { type: 'subscribe'; id: string; method: string; params: unknown[] }
    | { type: 'unsubscribe'; id: string }
    | { type: 'cancel'; id: string };

class SSETransport implements ClientTransport {
    private eventSource: EventSource | null = null;
    private connectionId: string | null = null;
    private baseUrl: string = '';
    private onMessage: ((data: string) => void) | null = null;

    connect(url: string, onMessage: (data: string) => void, onClose: (info?: TransportCloseInfo) => void): Promise<void> {
        this.baseUrl = url;
        this.onMessage = onMessage;

        return new Promise((resolve) => {
            this.eventSource = new EventSource(url);

            this.eventSource.addEventListener('connected', (e: MessageEvent) => {
                const msg = JSON.parse(e.data);
                this.connectionId = msg.connectionId;
                resolve();
            });

            this.eventSource.addEventListener('config', (e: MessageEvent) => {
                onMessage(e.data);
            });

            this.eventSource.addEventListener('response', (e: MessageEvent) => {
                onMessage(e.data);
            });

            this.eventSource.addEventListener('error', (e: MessageEvent) => {
                if (e.data) {
                    onMessage(e.data);
                } else {
                    // EventSource connection error (no data = connectivity issue).
                    // EventSource exposes nothing structured here, so the
                    // ApiClient classifier falls through to 'network-error'
                    // after offline/manual checks.
                    this.eventSource?.close();
                    this.eventSource = null;
                    this.connectionId = null;
                    onClose({ wasClean: false });
                }
            });

            this.eventSource.addEventListener('progress', (e: MessageEvent) => {
                onMessage(e.data);
            });

            this.eventSource.addEventListener('push', (e: MessageEvent) => {
                onMessage(e.data);
            });

            this.eventSource.addEventListener('stream_item', (e: MessageEvent) => {
                onMessage(e.data);
            });

            this.eventSource.addEventListener('stream_end', (e: MessageEvent) => {
                onMessage(e.data);
            });

        });
    }

    send(message: object): void {
        if (!this.connectionId) return;
        const msg = message as ClientMessage;

        if (msg.type === 'request' || msg.type === 'subscribe') {
            fetch(this.baseUrl + '/rpc', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    type: msg.type,
                    connectionId: this.connectionId,
                    id: msg.id,
                    method: msg.method,
                    params: msg.params,
                }),
            }).then((resp) => {
                if (resp.status !== 202) {
                    this.synthesizeError(msg.id, `Server returned unexpected response (status ${resp.status})`);
                }
            }).catch(() => {
                this.synthesizeError(msg.id, 'Network error: failed to send request');
            });
        } else if (msg.type === 'unsubscribe') {
            fetch(this.baseUrl + '/rpc', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    type: 'unsubscribe',
                    connectionId: this.connectionId,
                    id: msg.id,
                }),
            }).catch(() => {});
        } else if (msg.type === 'cancel') {
            fetch(this.baseUrl + '/cancel', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    connectionId: this.connectionId,
                    id: msg.id,
                }),
            }).catch(() => {});
        }
    }

    private synthesizeError(id: string, message: string): void {
        if (this.onMessage) {
            this.onMessage(JSON.stringify({ type: 'error', id, code: -32603, message }));
        }
    }

    disconnect(): void {
        this.eventSource?.close();
        this.eventSource = null;
        this.connectionId = null;
        this.onMessage = null;
    }

    isConnected(): boolean {
        return this.eventSource !== null && this.connectionId !== null;
    }
}

/**
 * url can be a string or a function returning a (possibly async) string.
 * When a function is provided it is called before every connection attempt,
 * allowing the caller to supply a fresh auth token on each reconnect.
 */
export type ApiClientUrl = string | (() => string | Promise<string>);

export class ApiClient {
    private transport: ClientTransport;
    private url: ApiClientUrl;
    private options: ResolvedOptions;
    private requestId = 0;
    private pending = new Map<string, {
        resolve: (value: unknown) => void;
        reject: (error: Error) => void;
        onProgress?: (current: number, total: number, message: string) => void;
        onMessage?: (msg: Record<string, unknown>) => void;
        onSettle?: () => void;
    }>();
    private buffer: Array<{
        method: string;
        params: unknown[];
        options?: RequestOptions;
        resolve: (value: unknown) => void;
        reject: (error: Error) => void;
    }> = [];
    private subscriptions = new Map<string, {
        method: string;
        params: unknown[];
        callback: (data: unknown) => void;
        onError?: (error: Error) => void;
    }>();
    private streams = new Map<string, {
        push: (item: unknown) => void;
        end: (err: Error | null) => void;
    }>();
    private pushHandlers = new Map<string, Set<(data: unknown) => void>>();
    private stateListeners = new Set<(state: ConnectionState) => void>();
    private loadingListeners = new Set<(count: number) => void>();
    private connectionErrorListeners = new Set<(error: ConnectionError) => void>();
    private lastLoadingCount = 0;
    private state: ConnectionState = 'disconnected';
    private reconnectAttempts = 0;
    private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
    private manualDisconnect = false;
    // pendingRejection is set when the server sends a ConnectionRejected
    // ApiError just before tearing down the transport. handleClose() reads
    // it so the resulting ConnectionError carries reason 'server-rejected'
    // (with the original ApiError as cause) rather than the default
    // 'manual' reading triggered by transport.disconnect().
    private pendingRejection: ApiError | null = null;
    // lastConnectionError is the most recently observed ConnectionError,
    // exposed via getLastConnectionError() so a UI can render an offline
    // banner / "server unreachable" message after the fact.
    private lastConnectionError: ConnectionError | null = null;
    private visibilityHandler: (() => void) | null = null;
    private onlineHandler: (() => void) | null = null;

    constructor(url: ApiClientUrl, options?: ApiClientOptions) {
        this.url = url;
        this.options = { ...defaultOptions, ...options };
        this.transport = this.options.transport === 'sse'
            ? new SSETransport()
            : new WebSocketTransport();
    }

    connect(): Promise<void> {
        if (this.state === 'connected' || this.state === 'connecting') {
            return Promise.resolve();
        }
        this.manualDisconnect = false;
        this.setupPageListeners();
        return this.doConnect();
    }

    private async doConnect(): Promise<void> {
        this.setState(this.reconnectAttempts > 0 ? 'reconnecting' : 'connecting');

        const url = typeof this.url === 'function' ? await this.url() : this.url;

        return this.transport.connect(
            url,
            (data) => this.handleMessage(data),
            (info) => this.handleClose(info),
        ).then(() => {
            this.reconnectAttempts = 0;
            this.setState('connected');
        }).catch(() => {
            // The transport's promise rejected before opening — treat as a
            // pre-upgrade close with no diagnostic info available.
            this.handleClose({ wasClean: false });
        });
    }

    // classifyClose decides why the transport closed. Order matters:
    //   1. Server-rejected wins because the server explicitly told us why
    //      (we keep the ApiError as `cause`).
    //   2. Manual disconnect comes next — the caller initiated the close.
    //   3. Offline overrides everything else; navigator.onLine being false
    //      means even a clean close happened during a network outage and
    //      "offline" is the more useful message.
    //   4. A close code outside the abnormal range (1006) and 0 means the
    //      WebSocket upgrade succeeded and the server closed cleanly.
    //   5. Otherwise the failure happened before/at upgrade time and the
    //      browser collapses every cause into an indistinguishable
    //      'network-error'.
    private classifyClose(info?: TransportCloseInfo): ConnectionErrorReason {
        if (this.pendingRejection || info?.serverRejected) {
            return 'server-rejected';
        }
        if (this.manualDisconnect) return 'manual';
        if (typeof navigator !== 'undefined' && navigator.onLine === false) {
            return 'offline';
        }
        if (info?.code !== undefined && info.code !== 1006 && info.code !== 0) {
            return 'server-closed';
        }
        return 'network-error';
    }

    private buildConnectionError(reason: ConnectionErrorReason, info?: TransportCloseInfo): ConnectionError {
        let message: string;
        const init: ConnectionErrorInit = {
            closeCode: info?.code,
            closeReason: info?.reason,
        };
        switch (reason) {
            case 'offline':
                message = 'Offline: no network connection';
                break;
            case 'server-rejected': {
                const cause = this.pendingRejection;
                init.cause = cause ?? undefined;
                message = cause?.message
                    ? `Server rejected connection: ${cause.message}`
                    : 'Server rejected connection';
                break;
            }
            case 'server-closed':
                message = info?.reason
                    ? `Server closed connection (code ${info.code}): ${info.reason}`
                    : `Server closed connection (code ${info?.code ?? 'unknown'})`;
                break;
            case 'network-error':
                message = 'Network error: connection lost';
                break;
            case 'manual':
                message = 'Disconnected';
                break;
        }
        return new ConnectionError(reason, message, init);
    }

    private notifyConnectionError(error: ConnectionError): void {
        this.lastConnectionError = error;
        for (const listener of this.connectionErrorListeners) {
            listener(error);
        }
    }

    private handleClose(info?: TransportCloseInfo): void {
        const reason = this.classifyClose(info);
        const error = this.buildConnectionError(reason, info);
        // Consume the pending rejection: subsequent reconnect attempts
        // (e.g. after the auth flow refreshes) must not be misclassified.
        this.pendingRejection = null;

        // Reject all pending requests (but keep subscription entries for reconnect)
        const subIds = new Set(this.subscriptions.keys());
        for (const [id, p] of this.pending) {
            if (!subIds.has(id)) {
                p.onSettle?.();
                p.reject(error);
            }
            this.pending.delete(id);
        }
        // End all in-flight streams with the structured connection error.
        // Streams are not auto-resumed on reconnect; consumers must restart
        // them.
        const streams = Array.from(this.streams.values());
        this.streams.clear();
        for (const s of streams) {
            s.end(error);
        }
        this.notifyLoadingChange();
        this.notifyConnectionError(error);

        if (this.manualDisconnect) {
            this.setState('disconnected');
            return;
        }

        // Auto-reconnect if enabled
        if (this.options.reconnect && (
            this.options.reconnectMaxAttempts === 0 ||
            this.reconnectAttempts < this.options.reconnectMaxAttempts
        )) {
            this.scheduleReconnect();
        } else {
            this.setState('disconnected');
        }
    }

    private scheduleReconnect(): void {
        if (this.reconnectTimer) return;

        const delay = Math.min(
            this.options.reconnectInterval * Math.pow(2, this.reconnectAttempts),
            this.options.reconnectMaxInterval
        );
        this.reconnectAttempts++;
        this.setState('reconnecting');

        this.reconnectTimer = setTimeout(() => {
            this.reconnectTimer = null;
            this.doConnect().catch(() => {
                // Error handled in handleClose
            });
        }, delay);
    }

    disconnect(): void {
        this.manualDisconnect = true;
        this.teardownPageListeners();
        if (this.reconnectTimer) {
            clearTimeout(this.reconnectTimer);
            this.reconnectTimer = null;
        }
        this.subscriptions.clear();
        this.transport.disconnect();
        this.setState('disconnected');
    }

    getState(): ConnectionState {
        return this.state;
    }

    private setState(state: ConnectionState): void {
        if (this.state === state) return;
        this.state = state;
        if (state === 'connected') {
            this.flushBuffer();
            this.resubscribeAll();
        } else if (state === 'disconnected') {
            // Reuse the most recent classified error if handleClose() just
            // ran, so a request buffered during a reconnect attempt that
            // ultimately fails is rejected with the same reason as the
            // close itself (e.g. 'offline'). Falls back to 'manual' when
            // there's no prior error — that branch is hit by an idle
            // disconnect() with no in-flight close.
            const err = this.lastConnectionError ?? new ConnectionError('manual', 'Not connected');
            this.rejectBuffer(err);
        }
        for (const listener of this.stateListeners) {
            listener(state);
        }
    }

    onStateChange(listener: (state: ConnectionState) => void): () => void {
        this.stateListeners.add(listener);
        return () => this.stateListeners.delete(listener);
    }

    onLoadingChange(listener: (count: number) => void): () => void {
        this.loadingListeners.add(listener);
        return () => this.loadingListeners.delete(listener);
    }

    /**
     * onConnectionError registers a listener that fires every time a
     * connection-level failure is classified (transport close, server
     * rejection, etc.). The listener receives a structured ConnectionError
     * carrying the reason and any close-event diagnostics the browser
     * exposed. Use this to drive UI like an "Offline" banner.
     *
     * Returns an unsubscribe function. Multiple listeners are supported.
     */
    onConnectionError(listener: (error: ConnectionError) => void): () => void {
        this.connectionErrorListeners.add(listener);
        return () => this.connectionErrorListeners.delete(listener);
    }

    /**
     * getLastConnectionError returns the most recent ConnectionError, or
     * null if no failure has been observed (or the connection has never
     * dropped). Useful right after `getState() === 'disconnected'` or
     * 'reconnecting' to decide what message to show the user.
     */
    getLastConnectionError(): ConnectionError | null {
        return this.lastConnectionError;
    }

    getLoadingCount(): number {
        let count = this.buffer.length + this.streams.size;
        for (const id of this.pending.keys()) {
            if (!this.subscriptions.has(id)) count++;
        }
        return count;
    }

    isConnected(): boolean {
        return this.state === 'connected';
    }

    private setupPageListeners(): void {
        if (typeof document === 'undefined') return;
        this.teardownPageListeners();

        this.visibilityHandler = () => {
            if (!document.hidden) this.handlePageWake();
        };
        this.onlineHandler = () => this.handlePageWake();

        document.addEventListener('visibilitychange', this.visibilityHandler);
        window.addEventListener('online', this.onlineHandler);
    }

    private teardownPageListeners(): void {
        if (typeof document === 'undefined') return;
        if (this.visibilityHandler) {
            document.removeEventListener('visibilitychange', this.visibilityHandler);
            this.visibilityHandler = null;
        }
        if (this.onlineHandler) {
            window.removeEventListener('online', this.onlineHandler);
            this.onlineHandler = null;
        }
    }

    private handlePageWake(): void {
        if (this.manualDisconnect) return;
        if (this.state === 'connected' && this.transport.isConnected()) return;
        if (this.state === 'connecting') return;

        if (this.reconnectTimer) {
            clearTimeout(this.reconnectTimer);
            this.reconnectTimer = null;
        }
        this.reconnectAttempts = 0;
        this.doConnect().catch(() => {});
    }

    private notifyLoadingChange(): void {
        // Read through getLoadingCount() so the listener-facing count and the
        // public getter cannot diverge. Subscription pending entries (added
        // by subscribe() and re-added by resubscribeAll() on reconnect) must
        // not flip useIsLoading() to true — otherwise reconnects after auth
        // refresh or coming back from another app leave the global loading
        // state stuck until every subscription's first response arrives.
        const count = this.getLoadingCount();
        if (count !== this.lastLoadingCount) {
            this.lastLoadingCount = count;
            for (const listener of this.loadingListeners) {
                listener(count);
            }
        }
    }

    private handleMessage(data: string): void {
        const msg = JSON.parse(data);
        switch (msg.type) {
            case 'config':
                this.applyConfig(msg);
                break;
            case 'response': {
                const p = this.pending.get(msg.id);
                if (p) {
                    this.pending.delete(msg.id);
                    p.onSettle?.();
                    p.resolve(msg.result);
                    this.notifyLoadingChange();
                } else {
                    // Server-driven subscription refresh
                    const sub = this.subscriptions.get(msg.id);
                    if (sub) {
                        sub.callback(msg.result);
                    }
                }
                break;
            }
            case 'error': {
                const p = this.pending.get(msg.id);
                if (p) {
                    this.pending.delete(msg.id);
                    p.onSettle?.();
                    p.reject(new ApiError(msg.code, msg.message, msg.data));
                    this.notifyLoadingChange();
                    break;
                }
                // Preflight errors from a streaming handler arrive as a
                // regular `error` envelope (not `stream_end`). Terminate the
                // stream with the error so the for-await loop throws.
                const stream = this.streams.get(msg.id);
                if (stream) {
                    this.streams.delete(msg.id);
                    stream.end(new ApiError(msg.code, msg.message, msg.data));
                    this.notifyLoadingChange();
                    break;
                }
                if (msg.code === ErrorCode.ConnectionRejected) {
                    const apiError = new ApiError(msg.code, msg.message, msg.data);
                    this.manualDisconnect = true;
                    // Stash the rejection so the imminent transport close
                    // is classified as 'server-rejected' rather than the
                    // default 'manual' that manualDisconnect=true would
                    // otherwise produce. handleClose() consumes it.
                    this.pendingRejection = apiError;
                    this.options.onConnectionRejected?.(apiError);
                    this.transport.disconnect();
                } else {
                    // Server-driven subscription refresh error
                    const sub = this.subscriptions.get(msg.id);
                    if (sub) {
                        sub.onError?.(new ApiError(msg.code, msg.message, msg.data));
                    }
                }
                break;
            }
            case 'progress': {
                const p = this.pending.get(msg.id);
                if (p) {
                    if (p.onProgress && (msg.current != null || msg.total != null || msg.message)) {
                        p.onProgress(msg.current ?? 0, msg.total ?? 0, msg.message ?? '');
                    }
                    p.onMessage?.(msg);
                }
                break;
            }
            case 'push': {
                const handlers = this.pushHandlers.get(msg.event);
                if (handlers) {
                    for (const handler of handlers) {
                        handler(msg.data);
                    }
                }
                break;
            }
            case 'stream_item': {
                const s = this.streams.get(msg.id);
                if (s) s.push(msg.item);
                break;
            }
            case 'stream_end': {
                const s = this.streams.get(msg.id);
                if (s) {
                    this.streams.delete(msg.id);
                    if (msg.code) {
                        s.end(new ApiError(msg.code, msg.message, msg.data));
                    } else {
                        s.end(null);
                    }
                    this.notifyLoadingChange();
                }
                break;
            }
        }
    }

    private applyConfig(config: {
        reconnectInterval?: number;
        reconnectMaxInterval?: number;
        reconnectMaxAttempts?: number;
    }): void {
        if (config.reconnectInterval !== undefined) {
            this.options.reconnectInterval = config.reconnectInterval;
        }
        if (config.reconnectMaxInterval !== undefined) {
            this.options.reconnectMaxInterval = config.reconnectMaxInterval;
        }
        if (config.reconnectMaxAttempts !== undefined) {
            this.options.reconnectMaxAttempts = config.reconnectMaxAttempts;
        }
    }

    request<T>(method: string, params: unknown[], options?: RequestOptions): Promise<T> {
        return new Promise((resolve, reject) => {
            const res = resolve as (value: unknown) => void;
            if (this.transport.isConnected()) {
                this.sendRequest(method, params, options, res, reject);
                return;
            }
            if (this.state === 'connecting' || this.state === 'reconnecting') {
                const entry = { method, params, options, resolve: res, reject };
                this.buffer.push(entry);
                this.notifyLoadingChange();
                if (options?.signal) {
                    if (options.signal.aborted) {
                        this.buffer.pop();
                        reject(new Error('Request aborted'));
                        this.notifyLoadingChange();
                        return;
                    }
                    options.signal.addEventListener('abort', () => {
                        const idx = this.buffer.indexOf(entry);
                        if (idx !== -1) {
                            this.buffer.splice(idx, 1);
                            reject(new Error('Request aborted'));
                            this.notifyLoadingChange();
                        }
                    }, { once: true });
                }
                return;
            }
            // Disconnected and not reconnecting. Prefer the most recent
            // ConnectionError (set by handleClose) so callers see the same
            // reason that classified the transport drop. If we got here
            // without a prior failure (e.g. caller never connected, or
            // navigator.onLine flipped between connect and request), still
            // surface a ConnectionError with the best reason we can name.
            let err = this.lastConnectionError;
            if (!err) {
                if (typeof navigator !== 'undefined' && navigator.onLine === false) {
                    err = new ConnectionError('offline', 'Offline: no network connection');
                } else {
                    err = new ConnectionError('manual', 'Not connected');
                }
            }
            reject(err);
        });
    }

    private sendRequest(method: string, params: unknown[], options: RequestOptions | undefined,
        resolve: (value: unknown) => void, reject: (error: Error) => void): void {
        const id = String(++this.requestId);
        const onSettle = options?._onSettle;
        this.pending.set(id, {
            resolve, reject,
            onProgress: options?.onProgress,
            onMessage: options?.onMessage,
            onSettle,
        });
        options?._onStart?.(id);
        if (options?.signal) {
            if (options.signal.aborted) {
                this.pending.delete(id);
                onSettle?.();
                reject(new Error('Request aborted'));
                this.notifyLoadingChange();
                return;
            }
            options.signal.addEventListener('abort', () => {
                const p = this.pending.get(id);
                if (p) {
                    this.pending.delete(id);
                    p.onSettle?.();
                }
                this.transport.send({ type: 'cancel', id });
                reject(new Error('Request aborted'));
                this.notifyLoadingChange();
            }, { once: true });
        }
        this.transport.send({ type: 'request', id, method, params });
        this.notifyLoadingChange();
    }

    private flushBuffer(): void {
        const buffered = this.buffer;
        this.buffer = [];
        for (const entry of buffered) {
            if (entry.options?.signal?.aborted) {
                entry.reject(new Error('Request aborted'));
                this.notifyLoadingChange();
                continue;
            }
            this.sendRequest(entry.method, entry.params, entry.options, entry.resolve, entry.reject);
        }
    }

    private rejectBuffer(error: Error): void {
        const buffered = this.buffer;
        this.buffer = [];
        for (const entry of buffered) {
            entry.reject(error);
        }
        this.notifyLoadingChange();
    }

    private resubscribeAll(): void {
        for (const [id, sub] of this.subscriptions) {
            this.pending.set(id, {
                resolve: (result) => { sub.callback(result); },
                reject: (err) => { sub.onError?.(err as Error); },
            });
            this.transport.send({ type: 'subscribe', id, method: sub.method, params: sub.params });
        }
        this.notifyLoadingChange();
    }

    onPush<T>(event: string, handler: PushHandler<T>): () => void {
        if (!this.pushHandlers.has(event)) {
            this.pushHandlers.set(event, new Set());
        }
        const cb = handler as (data: unknown) => void;
        this.pushHandlers.get(event)!.add(cb);
        return () => {
            this.pushHandlers.get(event)?.delete(cb);
        };
    }

    subscribe<T>(method: string, params: unknown[], callback: (data: T) => void, onError?: (error: Error) => void): () => void {
        const id = String(++this.requestId);
        const cb = callback as (data: unknown) => void;
        this.subscriptions.set(id, { method, params, callback: cb, onError });

        // Register in pending for the initial response
        this.pending.set(id, {
            resolve: (result) => { cb(result); },
            reject: (err) => { onError?.(err as Error); },
        });

        if (this.transport.isConnected()) {
            this.transport.send({ type: 'subscribe', id, method, params });
        }

        return () => {
            this.subscriptions.delete(id);
            this.pending.delete(id);
            if (this.transport.isConnected()) {
                this.transport.send({ type: 'unsubscribe', id });
            }
        };
    }

    /**
     * Opens a server-side streaming request and returns an AsyncIterable that
     * yields items as they arrive. Each call to `[Symbol.asyncIterator]()`
     * starts a fresh server request — the returned iterable is a factory,
     * not a singleton.
     *
     * Use with `for await`:
     * ```ts
     * for await (const user of streamUsers(client)) { ... }
     * ```
     *
     * Cancellation: breaking out of the `for await` loop, calling `.return()`
     * on the iterator, or aborting via `options.signal` sends a `cancel`
     * message to the server. Streams in flight at disconnect time are
     * rejected with an error and are NOT auto-resumed on reconnect.
     */
    requestStream<T>(method: string, params: unknown[], options?: RequestOptions): AsyncIterable<T> {
        // Arrow factory captures `this` lexically — avoids aliasing `this` to a
        // local variable (which trips @typescript-eslint/no-this-alias under
        // strict presets). All inner closures are also arrows, so they inherit
        // the same `this` (the ApiClient instance).
        return {
            [Symbol.asyncIterator]: (): AsyncIterator<T> => {
                let id = '';
                let started = false;
                const buffer: T[] = [];
                const waiters: Array<{
                    resolve: (r: IteratorResult<T>) => void;
                    reject: (e: Error) => void;
                }> = [];
                let ended = false;
                let endError: Error | null = null;

                const push = (item: unknown) => {
                    if (ended) return;
                    const w = waiters.shift();
                    if (w) {
                        w.resolve({ value: item as T, done: false });
                    } else {
                        buffer.push(item as T);
                    }
                };
                const end = (err: Error | null) => {
                    if (ended) return;
                    ended = true;
                    endError = err;
                    const pending = waiters.splice(0);
                    for (const w of pending) {
                        if (err) {
                            w.reject(err);
                        } else {
                            w.resolve({ value: undefined as unknown as T, done: true });
                        }
                    }
                };

                const cancelAtServer = () => {
                    if (id && !ended) {
                        this.streams.delete(id);
                        if (this.transport.isConnected()) {
                            this.transport.send({ type: 'cancel', id });
                        }
                    }
                };

                const ensureStarted = () => {
                    if (started) return;
                    started = true;
                    if (!this.transport.isConnected()) {
                        const err = this.lastConnectionError ?? (
                            typeof navigator !== 'undefined' && navigator.onLine === false
                                ? new ConnectionError('offline', 'Offline: no network connection')
                                : new ConnectionError('manual', 'Not connected')
                        );
                        end(err);
                        return;
                    }
                    id = String(++this.requestId);
                    this.streams.set(id, { push, end });
                    this.notifyLoadingChange();
                    if (options?.signal) {
                        if (options.signal.aborted) {
                            cancelAtServer();
                            end(new Error('Request aborted'));
                            return;
                        }
                        options.signal.addEventListener('abort', () => {
                            cancelAtServer();
                            end(new Error('Request aborted'));
                        }, { once: true });
                    }
                    this.transport.send({ type: 'request', id, method, params });
                };

                return {
                    next(): Promise<IteratorResult<T>> {
                        ensureStarted();
                        if (buffer.length > 0) {
                            return Promise.resolve({ value: buffer.shift()!, done: false });
                        }
                        if (ended) {
                            return endError
                                ? Promise.reject(endError)
                                : Promise.resolve({ value: undefined as unknown as T, done: true });
                        }
                        return new Promise((resolve, reject) => waiters.push({ resolve, reject }));
                    },
                    return(): Promise<IteratorResult<T>> {
                        cancelAtServer();
                        end(null);
                        return Promise.resolve({ value: undefined as unknown as T, done: true });
                    },
                    throw(err: unknown): Promise<IteratorResult<T>> {
                        cancelAtServer();
                        end(err instanceof Error ? err : new Error(String(err)));
                        return Promise.reject(err);
                    },
                };
            },
        };
    }
}

