// Code generated by aprot. DO NOT EDIT.


// Standard error codes
export const ErrorCode = {
    ParseError: -32700,
    InvalidRequest: -32600,
    MethodNotFound: -32601,
    InvalidParams: -32602,
    InternalError: -32603,
    Canceled: -32800,
    Unauthorized: -32001,
    ConnectionRejected: -32002,
    Forbidden: -32003,
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];



// ApiError is thrown when the server returns an error response
export class ApiError extends Error {
    readonly code: number;

    constructor(code: number, message: string) {
        super(message);
        this.name = 'ApiError';
        this.code = code;
    }

    // Helper methods for checking error types
    isUnauthorized(): boolean { return this.code === ErrorCode.Unauthorized; }
    isForbidden(): boolean { return this.code === ErrorCode.Forbidden; }
    isNotFound(): boolean { return this.code === ErrorCode.MethodNotFound; }
    isInvalidParams(): boolean { return this.code === ErrorCode.InvalidParams; }
    isCanceled(): boolean { return this.code === ErrorCode.Canceled; }
    isConnectionRejected(): boolean { return this.code === ErrorCode.ConnectionRejected; }
}



export interface RequestOptions {
    signal?: AbortSignal;
    onProgress?: (current: number, total: number, message: string) => void;
    onMessage?: (msg: Record<string, unknown>) => void;
    /** @internal Called with the allocated request ID before the request is sent. */
    _onStart?: (requestId: string) => void;
    /** @internal Called when the request settles (response, error, or cancel). */
    _onSettle?: () => void;
}

export type PushHandler<T> = (data: T) => void;

export type ConnectionState = 'disconnected' | 'connecting' | 'connected' | 'reconnecting';

export interface ApiClientOptions {
    /** Transport type. Default: 'websocket' */
    transport?: 'websocket' | 'sse';
    /** Enable auto-reconnect on connection loss. Default: true */
    reconnect?: boolean;
    /** Initial reconnect delay in ms. Default: 1000 */
    reconnectInterval?: number;
    /** Maximum reconnect delay in ms (for exponential backoff). Default: 30000 */
    reconnectMaxInterval?: number;
    /** Maximum reconnect attempts. 0 = unlimited. Default: 0 */
    reconnectMaxAttempts?: number;
    /** Called when the server rejects the connection (e.g. invalid session). Connection will not auto-reconnect. */
    onConnectionRejected?: (error: ApiError) => void;
}

type ResolvedOptions = Required<Omit<ApiClientOptions, 'onConnectionRejected'>> & Pick<ApiClientOptions, 'onConnectionRejected'>;

const defaultOptions: ResolvedOptions = {
    transport: 'websocket',
    reconnect: true,
    reconnectInterval: 1000,
    reconnectMaxInterval: 30000,
    reconnectMaxAttempts: 0,
};



/**
 * Returns a WebSocket URL based on the current page location.
 * Automatically uses wss: for https: pages and ws: for http: pages.
 * @param path - The WebSocket endpoint path (default: '/ws')
 */
export function getWebSocketUrl(path: string = '/ws'): string {
    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    return `${protocol}//${window.location.host}${path}`;
}

/**
 * Returns an SSE base URL based on the current page location.
 * @param path - The SSE endpoint base path (default: '/sse')
 */
export function getSSEUrl(path: string = '/sse'): string {
    return `${window.location.protocol}//${window.location.host}${path}`;
}



// Internal transport interface
interface ClientTransport {
    connect(url: string, onMessage: (data: string) => void, onClose: () => void): Promise<void>;
    send(message: object): void;
    disconnect(): void;
    isConnected(): boolean;
}

class WebSocketTransport implements ClientTransport {
    private ws: WebSocket | null = null;

    connect(url: string, onMessage: (data: string) => void, onClose: () => void): Promise<void> {
        return new Promise((resolve) => {
            this.ws = new WebSocket(url);
            this.ws.onopen = () => resolve();
            this.ws.onerror = () => {}; // Error is followed by close
            this.ws.onmessage = (e) => onMessage(e.data);
            this.ws.onclose = () => {
                this.ws = null;
                onClose();
            };
        });
    }

    send(message: object): void {
        this.ws?.send(JSON.stringify(message));
    }

    disconnect(): void {
        this.ws?.close();
        this.ws = null;
    }

    isConnected(): boolean {
        return this.ws !== null && this.ws.readyState === WebSocket.OPEN;
    }
}

type ClientMessage =
    | { type: 'request'; id: string; method: string; params: unknown[] }
    | { type: 'subscribe'; id: string; method: string; params: unknown[] }
    | { type: 'unsubscribe'; id: string }
    | { type: 'cancel'; id: string };

class SSETransport implements ClientTransport {
    private eventSource: EventSource | null = null;
    private connectionId: string | null = null;
    private baseUrl: string = '';
    private onMessage: ((data: string) => void) | null = null;

    connect(url: string, onMessage: (data: string) => void, onClose: () => void): Promise<void> {
        this.baseUrl = url;
        this.onMessage = onMessage;

        return new Promise((resolve) => {
            this.eventSource = new EventSource(url);

            this.eventSource.addEventListener('connected', (e: MessageEvent) => {
                const msg = JSON.parse(e.data);
                this.connectionId = msg.connectionId;
                resolve();
            });

            this.eventSource.addEventListener('config', (e: MessageEvent) => {
                onMessage(e.data);
            });

            this.eventSource.addEventListener('response', (e: MessageEvent) => {
                onMessage(e.data);
            });

            this.eventSource.addEventListener('error', (e: MessageEvent) => {
                if (e.data) {
                    onMessage(e.data);
                } else {
                    // EventSource connection error (no data = connectivity issue)
                    this.eventSource?.close();
                    this.eventSource = null;
                    this.connectionId = null;
                    onClose();
                }
            });

            this.eventSource.addEventListener('progress', (e: MessageEvent) => {
                onMessage(e.data);
            });

            this.eventSource.addEventListener('push', (e: MessageEvent) => {
                onMessage(e.data);
            });

        });
    }

    send(message: object): void {
        if (!this.connectionId) return;
        const msg = message as ClientMessage;

        if (msg.type === 'request' || msg.type === 'subscribe') {
            fetch(this.baseUrl + '/rpc', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    type: msg.type,
                    connectionId: this.connectionId,
                    id: msg.id,
                    method: msg.method,
                    params: msg.params,
                }),
            }).then((resp) => {
                if (resp.status !== 202) {
                    this.synthesizeError(msg.id, `Server returned unexpected response (status ${resp.status})`);
                }
            }).catch(() => {
                this.synthesizeError(msg.id, 'Network error: failed to send request');
            });
        } else if (msg.type === 'unsubscribe') {
            fetch(this.baseUrl + '/rpc', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    type: 'unsubscribe',
                    connectionId: this.connectionId,
                    id: msg.id,
                }),
            }).catch(() => {});
        } else if (msg.type === 'cancel') {
            fetch(this.baseUrl + '/cancel', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    connectionId: this.connectionId,
                    id: msg.id,
                }),
            }).catch(() => {});
        }
    }

    private synthesizeError(id: string, message: string): void {
        if (this.onMessage) {
            this.onMessage(JSON.stringify({ type: 'error', id, code: -32603, message }));
        }
    }

    disconnect(): void {
        this.eventSource?.close();
        this.eventSource = null;
        this.connectionId = null;
        this.onMessage = null;
    }

    isConnected(): boolean {
        return this.eventSource !== null && this.connectionId !== null;
    }
}

export class ApiClient {
    private transport: ClientTransport;
    private url: string;
    private options: ResolvedOptions;
    private requestId = 0;
    private pending = new Map<string, {
        resolve: (value: unknown) => void;
        reject: (error: Error) => void;
        onProgress?: (current: number, total: number, message: string) => void;
        onMessage?: (msg: Record<string, unknown>) => void;
        onSettle?: () => void;
    }>();
    private buffer: Array<{
        method: string;
        params: unknown[];
        options?: RequestOptions;
        resolve: (value: unknown) => void;
        reject: (error: Error) => void;
    }> = [];
    private subscriptions = new Map<string, {
        method: string;
        params: unknown[];
        callback: (data: unknown) => void;
        onError?: (error: Error) => void;
    }>();
    private pushHandlers = new Map<string, Set<(data: unknown) => void>>();
    private stateListeners = new Set<(state: ConnectionState) => void>();
    private loadingListeners = new Set<(count: number) => void>();
    private lastLoadingCount = 0;
    private state: ConnectionState = 'disconnected';
    private reconnectAttempts = 0;
    private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
    private manualDisconnect = false;
    private visibilityHandler: (() => void) | null = null;
    private onlineHandler: (() => void) | null = null;

    constructor(url: string, options?: ApiClientOptions) {
        this.url = url;
        this.options = { ...defaultOptions, ...options };
        this.transport = this.options.transport === 'sse'
            ? new SSETransport()
            : new WebSocketTransport();
    }

    connect(): Promise<void> {
        if (this.state === 'connected' || this.state === 'connecting') {
            return Promise.resolve();
        }
        this.manualDisconnect = false;
        this.setupPageListeners();
        return this.doConnect();
    }

    private doConnect(): Promise<void> {
        this.setState(this.reconnectAttempts > 0 ? 'reconnecting' : 'connecting');

        return this.transport.connect(
            this.url,
            (data) => this.handleMessage(data),
            () => this.handleClose(),
        ).then(() => {
            this.reconnectAttempts = 0;
            this.setState('connected');
        }).catch(() => {
            this.handleClose();
        });
    }

    private handleClose(): void {
        // Reject all pending requests (but keep subscription entries for reconnect)
        const subIds = new Set(this.subscriptions.keys());
        for (const [id, p] of this.pending) {
            if (!subIds.has(id)) {
                p.onSettle?.();
                p.reject(new Error('Connection closed'));
            }
            this.pending.delete(id);
        }
        this.notifyLoadingChange();

        if (this.manualDisconnect) {
            this.setState('disconnected');
            return;
        }

        // Auto-reconnect if enabled
        if (this.options.reconnect && (
            this.options.reconnectMaxAttempts === 0 ||
            this.reconnectAttempts < this.options.reconnectMaxAttempts
        )) {
            this.scheduleReconnect();
        } else {
            this.setState('disconnected');
        }
    }

    private scheduleReconnect(): void {
        if (this.reconnectTimer) return;

        const delay = Math.min(
            this.options.reconnectInterval * Math.pow(2, this.reconnectAttempts),
            this.options.reconnectMaxInterval
        );
        this.reconnectAttempts++;
        this.setState('reconnecting');

        this.reconnectTimer = setTimeout(() => {
            this.reconnectTimer = null;
            this.doConnect().catch(() => {
                // Error handled in handleClose
            });
        }, delay);
    }

    disconnect(): void {
        this.manualDisconnect = true;
        this.teardownPageListeners();
        if (this.reconnectTimer) {
            clearTimeout(this.reconnectTimer);
            this.reconnectTimer = null;
        }
        this.subscriptions.clear();
        this.transport.disconnect();
        this.setState('disconnected');
    }

    getState(): ConnectionState {
        return this.state;
    }

    private setState(state: ConnectionState): void {
        if (this.state === state) return;
        this.state = state;
        if (state === 'connected') {
            this.flushBuffer();
            this.resubscribeAll();
        } else if (state === 'disconnected') {
            this.rejectBuffer(new Error('Not connected'));
        }
        for (const listener of this.stateListeners) {
            listener(state);
        }
    }

    onStateChange(listener: (state: ConnectionState) => void): () => void {
        this.stateListeners.add(listener);
        return () => this.stateListeners.delete(listener);
    }

    onLoadingChange(listener: (count: number) => void): () => void {
        this.loadingListeners.add(listener);
        return () => this.loadingListeners.delete(listener);
    }

    getLoadingCount(): number {
        return this.pending.size + this.buffer.length;
    }

    /** @deprecated Use onStateChange instead */
    onConnectionChange(listener: (connected: boolean) => void): () => void {
        const wrapper = (state: ConnectionState) => listener(state === 'connected');
        this.stateListeners.add(wrapper);
        return () => this.stateListeners.delete(wrapper);
    }

    isConnected(): boolean {
        return this.state === 'connected';
    }

    private setupPageListeners(): void {
        if (typeof document === 'undefined') return;
        this.teardownPageListeners();

        this.visibilityHandler = () => {
            if (!document.hidden) this.handlePageWake();
        };
        this.onlineHandler = () => this.handlePageWake();

        document.addEventListener('visibilitychange', this.visibilityHandler);
        window.addEventListener('online', this.onlineHandler);
    }

    private teardownPageListeners(): void {
        if (typeof document === 'undefined') return;
        if (this.visibilityHandler) {
            document.removeEventListener('visibilitychange', this.visibilityHandler);
            this.visibilityHandler = null;
        }
        if (this.onlineHandler) {
            window.removeEventListener('online', this.onlineHandler);
            this.onlineHandler = null;
        }
    }

    private handlePageWake(): void {
        if (this.manualDisconnect) return;
        if (this.state === 'connected' && this.transport.isConnected()) return;
        if (this.state === 'connecting') return;

        if (this.reconnectTimer) {
            clearTimeout(this.reconnectTimer);
            this.reconnectTimer = null;
        }
        this.reconnectAttempts = 0;
        this.doConnect().catch(() => {});
    }

    private notifyLoadingChange(): void {
        const count = this.pending.size + this.buffer.length;
        if (count !== this.lastLoadingCount) {
            this.lastLoadingCount = count;
            for (const listener of this.loadingListeners) {
                listener(count);
            }
        }
    }

    private handleMessage(data: string): void {
        const msg = JSON.parse(data);
        switch (msg.type) {
            case 'config':
                this.applyConfig(msg);
                break;
            case 'response': {
                const p = this.pending.get(msg.id);
                if (p) {
                    this.pending.delete(msg.id);
                    p.onSettle?.();
                    p.resolve(msg.result);
                    this.notifyLoadingChange();
                } else {
                    // Server-driven subscription refresh
                    const sub = this.subscriptions.get(msg.id);
                    if (sub) {
                        sub.callback(msg.result);
                    }
                }
                break;
            }
            case 'error': {
                const p = this.pending.get(msg.id);
                if (p) {
                    this.pending.delete(msg.id);
                    p.onSettle?.();
                    p.reject(new ApiError(msg.code, msg.message));
                    this.notifyLoadingChange();
                } else if (msg.code === ErrorCode.ConnectionRejected) {
                    this.manualDisconnect = true;
                    this.options.onConnectionRejected?.(new ApiError(msg.code, msg.message));
                    this.transport.disconnect();
                } else {
                    // Server-driven subscription refresh error
                    const sub = this.subscriptions.get(msg.id);
                    if (sub) {
                        sub.onError?.(new ApiError(msg.code, msg.message));
                    }
                }
                break;
            }
            case 'progress': {
                const p = this.pending.get(msg.id);
                if (p) {
                    if (p.onProgress && (msg.current != null || msg.total != null || msg.message)) {
                        p.onProgress(msg.current ?? 0, msg.total ?? 0, msg.message ?? '');
                    }
                    p.onMessage?.(msg);
                }
                break;
            }
            case 'push': {
                const handlers = this.pushHandlers.get(msg.event);
                if (handlers) {
                    for (const handler of handlers) {
                        handler(msg.data);
                    }
                }
                break;
            }
        }
    }

    private applyConfig(config: {
        reconnectInterval?: number;
        reconnectMaxInterval?: number;
        reconnectMaxAttempts?: number;
    }): void {
        if (config.reconnectInterval !== undefined) {
            this.options.reconnectInterval = config.reconnectInterval;
        }
        if (config.reconnectMaxInterval !== undefined) {
            this.options.reconnectMaxInterval = config.reconnectMaxInterval;
        }
        if (config.reconnectMaxAttempts !== undefined) {
            this.options.reconnectMaxAttempts = config.reconnectMaxAttempts;
        }
    }

    request<T>(method: string, params: unknown[], options?: RequestOptions): Promise<T> {
        return new Promise((resolve, reject) => {
            const res = resolve as (value: unknown) => void;
            if (this.transport.isConnected()) {
                this.sendRequest(method, params, options, res, reject);
                return;
            }
            if (this.state === 'connecting' || this.state === 'reconnecting') {
                const entry = { method, params, options, resolve: res, reject };
                this.buffer.push(entry);
                this.notifyLoadingChange();
                if (options?.signal) {
                    if (options.signal.aborted) {
                        this.buffer.pop();
                        reject(new Error('Request aborted'));
                        this.notifyLoadingChange();
                        return;
                    }
                    options.signal.addEventListener('abort', () => {
                        const idx = this.buffer.indexOf(entry);
                        if (idx !== -1) {
                            this.buffer.splice(idx, 1);
                            reject(new Error('Request aborted'));
                            this.notifyLoadingChange();
                        }
                    }, { once: true });
                }
                return;
            }
            reject(new Error('Not connected'));
        });
    }

    private sendRequest(method: string, params: unknown[], options: RequestOptions | undefined,
        resolve: (value: unknown) => void, reject: (error: Error) => void): void {
        const id = String(++this.requestId);
        const onSettle = options?._onSettle;
        this.pending.set(id, {
            resolve, reject,
            onProgress: options?.onProgress,
            onMessage: options?.onMessage,
            onSettle,
        });
        options?._onStart?.(id);
        if (options?.signal) {
            if (options.signal.aborted) {
                this.pending.delete(id);
                onSettle?.();
                reject(new Error('Request aborted'));
                this.notifyLoadingChange();
                return;
            }
            options.signal.addEventListener('abort', () => {
                const p = this.pending.get(id);
                if (p) {
                    this.pending.delete(id);
                    p.onSettle?.();
                }
                this.transport.send({ type: 'cancel', id });
                reject(new Error('Request aborted'));
                this.notifyLoadingChange();
            }, { once: true });
        }
        this.transport.send({ type: 'request', id, method, params });
        this.notifyLoadingChange();
    }

    private flushBuffer(): void {
        const buffered = this.buffer;
        this.buffer = [];
        for (const entry of buffered) {
            if (entry.options?.signal?.aborted) {
                entry.reject(new Error('Request aborted'));
                this.notifyLoadingChange();
                continue;
            }
            this.sendRequest(entry.method, entry.params, entry.options, entry.resolve, entry.reject);
        }
    }

    private rejectBuffer(error: Error): void {
        const buffered = this.buffer;
        this.buffer = [];
        for (const entry of buffered) {
            entry.reject(error);
        }
        this.notifyLoadingChange();
    }

    private resubscribeAll(): void {
        for (const [id, sub] of this.subscriptions) {
            this.pending.set(id, {
                resolve: (result) => { sub.callback(result); },
                reject: (err) => { sub.onError?.(err as Error); },
            });
            this.transport.send({ type: 'subscribe', id, method: sub.method, params: sub.params });
        }
    }

    onPush<T>(event: string, handler: PushHandler<T>): () => void {
        if (!this.pushHandlers.has(event)) {
            this.pushHandlers.set(event, new Set());
        }
        const cb = handler as (data: unknown) => void;
        this.pushHandlers.get(event)!.add(cb);
        return () => {
            this.pushHandlers.get(event)?.delete(cb);
        };
    }

    subscribe<T>(method: string, params: unknown[], callback: (data: T) => void, onError?: (error: Error) => void): () => void {
        const id = String(++this.requestId);
        const cb = callback as (data: unknown) => void;
        this.subscriptions.set(id, { method, params, callback: cb, onError });

        // Register in pending for the initial response
        this.pending.set(id, {
            resolve: (result) => { cb(result); },
            reject: (err) => { onError?.(err as Error); },
        });

        if (this.transport.isConnected()) {
            this.transport.send({ type: 'subscribe', id, method, params });
        }

        return () => {
            this.subscriptions.delete(id);
            this.pending.delete(id);
            if (this.transport.isConnected()) {
                this.transport.send({ type: 'unsubscribe', id });
            }
        };
    }
}

