// Code generated by aprot. DO NOT EDIT.


// Standard error codes
export const ErrorCode = {
    ParseError: -32700,
    InvalidRequest: -32600,
    MethodNotFound: -32601,
    InvalidParams: -32602,
    InternalError: -32603,
    ValidationFailed: -32604,
    Canceled: -32800,
    Unauthorized: -32001,
    ConnectionRejected: -32002,
    Forbidden: -32003,
    TooManyRequests: -32004,
    AuthFailed: -32005,
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];



// FieldError is one entry in the structured payload that the server returns
// alongside CodeValidationFailed (-32604) responses. The shape mirrors the Go
// FieldError struct in validate.go on the server side.
export interface FieldError {
    field: string;
    tag: string;
    value: unknown;
    param: string;
    message: string;
}

// ApiError is thrown when the server returns an error response
export class ApiError extends Error {
    readonly code: number;
    // data is the structured payload the server attached to the error, if any.
    // For CodeValidationFailed responses this is FieldError[]; for other codes
    // it may be undefined or carry a code-specific shape. Use getValidationErrors
    // to safely extract field-level validation failures.
    readonly data?: unknown;

    constructor(code: number, message: string, data?: unknown) {
        super(message);
        this.name = 'ApiError';
        this.code = code;
        this.data = data;
    }

    // Helper methods for checking error types
    isUnauthorized(): boolean { return this.code === ErrorCode.Unauthorized; }
    isForbidden(): boolean { return this.code === ErrorCode.Forbidden; }
    isNotFound(): boolean { return this.code === ErrorCode.MethodNotFound; }
    isInvalidParams(): boolean { return this.code === ErrorCode.InvalidParams; }
    isValidationFailed(): boolean { return this.code === ErrorCode.ValidationFailed; }
    isCanceled(): boolean { return this.code === ErrorCode.Canceled; }
    isConnectionRejected(): boolean { return this.code === ErrorCode.ConnectionRejected; }
    isTooManyRequests(): boolean { return this.code === ErrorCode.TooManyRequests; }
    isAuthFailed(): boolean { return this.code === ErrorCode.AuthFailed; }
}

// getValidationErrors returns the structured FieldError list when err is a
// validation failure (code -32604), or null otherwise. Use this instead of
// hand-rolling the instanceof + code check + Array.isArray + cast pattern.
export function getValidationErrors(err: unknown): FieldError[] | null {
    if (!(err instanceof ApiError)) return null;
    if (err.code !== ErrorCode.ValidationFailed) return null;
    if (!Array.isArray(err.data)) return null;
    return err.data as FieldError[];
}

/**
 * Options for {@link ApiClient.subscribe} and generated `subscribeX` helpers.
 */
export interface SubscribeOptions {
    /**
     * Called when the server pushes a `subscription_patch` frame for this
     * subscription (see the server-side `aprot.PatchSubscription`). Providing
     * it declares patch support to the server; without it, the server falls
     * back to a full refresh (re-running the query and re-sending the result).
     * The patch payload is whatever the mutation handler pushed — apply it to
     * your local copy of the data.
     */
    onPatch?: (patch: unknown) => void;
}

/**
 * Builds an `applyPatch` reducer for the common case: the subscribed result
 * is an array of objects with a unique key field, and patches are partial
 * objects (or arrays of them) carrying that key. Entries matching a patch's
 * key are shallow-merged; patches with no matching entry are ignored — use a
 * full refresh (server-side `TriggerRefresh`) for structural changes like
 * added or removed items.
 *
 *   const { data } = useListPhotos({ applyPatch: mergeByKey('id') });
 *
 * For wrapped results (e.g. `{ photos: Photo[] }`) or richer semantics,
 * write the reducer by hand: `(data, patch) => ({ ...data, photos: ... })`.
 */
export function mergeByKey<T extends object>(key: keyof T & string): (data: T[], patch: unknown) => T[] {
    return (data: T[], patch: unknown): T[] => {
        const patches = (Array.isArray(patch) ? patch : [patch]) as Array<Partial<T> & Record<string, unknown>>;
        const byKey = new Map<unknown, Partial<T>>();
        for (const p of patches) {
            if (p && typeof p === 'object' && key in p) byKey.set(p[key], p);
        }
        if (byKey.size === 0) return data;
        return data.map((item) => {
            const p = byKey.get((item as Record<string, unknown>)[key]);
            return p ? { ...item, ...p } : item;
        });
    };
}

// Shared decoder for binary frame headers — small and reused per message.
const binaryHeaderDecoder = new TextDecoder();

// decodeBlobResult converts the server's JSON fallback for a Blob result —
// an object whose only key is "$blob" carrying { contentType?, data(base64) } —
// into a DOM Blob, so callers see the same type the binary path delivers.
// Any other result value passes through untouched.
function decodeBlobResult(result: unknown): unknown {
    if (
        result === null || typeof result !== 'object' || Array.isArray(result)
        || !('$blob' in result) || Object.keys(result).length !== 1
    ) {
        return result;
    }
    const b = (result as { $blob: { contentType?: string; data?: string } }).$blob;
    if (b === null || typeof b !== 'object') return result;
    const bin = atob(b.data ?? '');
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return new Blob([bytes], b.contentType ? { type: b.contentType } : undefined);
}

// ConnectionErrorReason classifies why a connection failed or could not be
// used. Browsers deliberately collapse most pre-WebSocket-upgrade failures
// (DNS, TCP refused, TLS handshake, HTTP 4xx during upgrade) into close
// code 1006 with no diagnostic text, so finer-grained classification is
// not achievable from JS — these all surface as 'network-error'.
//
//   - 'offline':         navigator.onLine was false at failure time.
//   - 'server-rejected': server sent an ApiError with code ConnectionRejected
//                        (e.g. invalid session) before closing. The original
//                        ApiError is attached via ConnectionError.cause.
//   - 'server-closed':   transport closed cleanly after the WebSocket upgrade
//                        completed; closeCode and closeReason are populated.
//   - 'network-error':   pre-upgrade failure or close code 1006 — refused,
//                        unreachable, TLS or upgrade-time HTTP error.
//   - 'connect-params-failed': the URL function or getConnectParams threw
//                        before any transport activity (e.g. a token
//                        provider fetch failed). The thrown error is
//                        attached via ConnectionError.cause. The normal
//                        reconnect backoff still applies.
//   - 'manual':          the caller invoked client.disconnect().
export type ConnectionErrorReason =
    | 'offline'
    | 'server-rejected'
    | 'server-closed'
    | 'network-error'
    | 'connect-params-failed'
    | 'manual';

// ConnectionErrorInit carries the optional diagnostic fields attached to a
// ConnectionError. closeCode/closeReason mirror the WebSocket CloseEvent
// fields when available; cause carries the underlying ApiError for
// 'server-rejected' so callers can read err.cause.code / err.cause.data.
export interface ConnectionErrorInit {
    closeCode?: number;
    closeReason?: string;
    cause?: unknown;
}

// ConnectionError is thrown (or attached to a rejected promise) whenever a
// request fails because the connection itself is unhealthy — distinct from
// ApiError, which represents a structured server-side error response. It
// extends Error so existing `catch (err) { ... }` blocks keep working; new
// code can switch on err.reason for user-facing messaging.
export class ConnectionError extends Error {
    readonly reason: ConnectionErrorReason;
    readonly closeCode?: number;
    readonly closeReason?: string;
    // cause is the underlying ApiError for 'server-rejected', if any.
    // For other reasons it is undefined. Typed `unknown` to align with the
    // ES2022 Error.cause convention without forcing a specific shape.
    readonly cause?: unknown;

    constructor(reason: ConnectionErrorReason, message: string, init?: ConnectionErrorInit) {
        super(message);
        this.name = 'ConnectionError';
        this.reason = reason;
        this.closeCode = init?.closeCode;
        this.closeReason = init?.closeReason;
        this.cause = init?.cause;
    }

    isOffline(): boolean { return this.reason === 'offline'; }
    isServerRejected(): boolean { return this.reason === 'server-rejected'; }
    isServerClosed(): boolean { return this.reason === 'server-closed'; }
    isNetworkError(): boolean { return this.reason === 'network-error'; }
    isConnectParamsFailed(): boolean { return this.reason === 'connect-params-failed'; }
    isManual(): boolean { return this.reason === 'manual'; }
}




// ApiClientErrorSource identifies which generated call produced an error. The
// wire name of every generated call is "Struct.Method" (e.g. "Todos.CreateTodo"),
// so struct names the handler/namespace and method names the operation. If a
// caller invokes the client with a name that has no dot, struct is the empty
// string and method holds the full wire name.
export interface ApiClientErrorSource {
    struct: string;
    method: string;
}

// parseMethodSource splits a "Struct.Method" wire name into the source object
// reported to <ApiClientErrorProvider>. Split on the first dot only.
function parseMethodSource(wireMethod: string): ApiClientErrorSource {
    const dot = wireMethod.indexOf('.');
    if (dot < 0) return { struct: '', method: wireMethod };
    return { struct: wireMethod.slice(0, dot), method: wireMethod.slice(dot + 1) };
}

export interface RequestOptions {
    signal?: AbortSignal;
    onProgress?: (current: number, total: number, message: string) => void;
    onMessage?: (msg: Record<string, unknown>) => void;
    /** @internal Called with the allocated request ID before the request is sent. */
    _onStart?: (requestId: string) => void;
    /** @internal Called when the request settles (response, error, or cancel). */
    _onSettle?: () => void;
}

export type PushHandler<T> = (data: T) => void;

export type ConnectionState = 'disconnected' | 'connecting' | 'connected' | 'reconnecting';

/**
 * TransportCloseInfo carries WebSocket CloseEvent diagnostics from the
 * transport up to the client's classification logic. Transports without an
 * equivalent (SSE, custom transports) may pass an empty object or nothing.
 */
export interface TransportCloseInfo {
    /** WebSocket CloseEvent.code, when available. 1006 = abnormal (pre-upgrade) closure. */
    code?: number;
    /** WebSocket CloseEvent.reason, when non-empty. */
    reason?: string;
    /** WebSocket CloseEvent.wasClean — true only if a close handshake completed. */
    wasClean?: boolean;
    /** True when the close was already classified as a server-rejected protocol error. */
    serverRejected?: boolean;
}

/**
 * ClientTransport is the connection layer under ApiClient. Two built-in
 * implementations exist (WebSocket and SSE, selected via
 * ApiClientOptions.transport as a string), but an instance implementing this
 * interface can be passed instead to carry the protocol over any message
 * channel — for example an Electron preload/MessagePort bridge to a Go
 * child process, where the renderer cannot open pipes itself.
 *
 * Contract:
 * - connect() resolves once the channel is ready; deliver every inbound
 *   protocol message to onMessage as a JSON string, and call onClose exactly
 *   once when the channel ends (after a successful connect).
 * - connect() must settle within a bounded time (the built-in transports
 *   give up after ApiClientOptions.connectTimeout). A promise that never
 *   settles pins the client in 'connecting', where connect() is a no-op
 *   and nothing can start a fresh attempt.
 * - send() receives a protocol message object; serialize it (e.g.
 *   JSON.stringify) onto the channel.
 * - The client calls connect() again for reconnects; a transport instance
 *   must be reusable after disconnect()/onClose.
 */
export interface ClientTransport {
    connect(url: string, onMessage: (data: string | Blob | ArrayBuffer) => void, onClose: (info?: TransportCloseInfo) => void): Promise<void>;
    send(message: object): void;
    disconnect(): void;
    isConnected(): boolean;
}

export interface ApiClientOptions {
    /**
     * Transport: 'websocket', 'sse', or a custom ClientTransport instance
     * (e.g. an Electron IPC/MessagePort bridge). Default: 'websocket'
     */
    transport?: 'websocket' | 'sse' | ClientTransport;
    /** Enable auto-reconnect on connection loss. Default: true */
    reconnect?: boolean;
    /** Reconnect delay step in ms: attempt n waits n × this (linear backoff). Default: 1000 */
    reconnectInterval?: number;
    /** Maximum reconnect delay in ms (caps the linear backoff). Default: 10000 */
    reconnectMaxInterval?: number;
    /** Maximum reconnect attempts. 0 = unlimited. Default: 0 */
    reconnectMaxAttempts?: number;
    /**
     * Milliseconds to wait for the transport handshake before giving up on
     * the attempt. Applies to the built-in WebSocket and SSE transports; a
     * custom ClientTransport enforces its own bound. Without one, a
     * handshake that black-holes (e.g. into a dead network path right after
     * wake) pins the client in 'connecting' for the browser's own TCP
     * timeout — often 20-30s — and connect()/reconnectNow() cannot
     * interrupt an attempt already in flight. A timed-out attempt fails
     * like any transport error, so the normal reconnect path applies.
     * 0 disables the timeout. Default: 10000
     */
    connectTimeout?: number;
    /**
     * Called when the server rejects the connection (e.g. invalid session).
     * The connection will not auto-reconnect unless reconnectOnRejected is set.
     */
    onConnectionRejected?: (error: ApiError) => void;
    /**
     * Retry after the server rejects the connection, instead of treating the
     * rejection as terminal. Default: false — a rejection stops auto-reconnect,
     * which is the right response to a real sign-out. Enable it for short-lived
     * credentials, where a rejection is usually a stale token, propagation delay
     * just after sign-in, or clock skew: pair it with getConnectParams /
     * getAuthToken so every retry carries a freshly minted token.
     *
     * `true` uses the defaults below. onConnectionRejected still fires on every
     * rejection. A retry that fails at the network level falls through to the
     * normal reconnect backoff. Unlike the reconnect settings, this is never
     * overridden by the server's config frame.
     */
    reconnectOnRejected?: boolean | {
        /** Delay before each retry in ms. Default: 2000 */
        delayMs?: number;
        /** Max consecutive rejection retries; 0 = unlimited. Reset by a successful connect. Default: 0 */
        maxAttempts?: number;
    };
    /**
     * Returns query parameters to append to the connection URL, resolved fresh
     * on every connection attempt — the initial connect, every auto-reconnect,
     * every rejection retry, and page-wake reconnects. This is the intended way
     * to carry a short-lived credential in the query string while keeping the
     * base URL static:
     *
     *     new ApiClient(getWebSocketUrl(), {
     *         getConnectParams: async () => ({ token: await getToken() }),
     *     })
     *
     * Values are URL-encoded by the client and override same-named parameters
     * already present in the URL. A thrown error (or rejected promise) fails the
     * attempt like a transport error, so the normal reconnect path applies.
     */
    getConnectParams?: () => Record<string, string> | Promise<Record<string, string>>;
    /**
     * Returns an auth token for first-message authentication. Called on the
     * initial connect and on every reconnect. When set, the client sends the
     * token as its first message ({type:'auth'}) and waits for the server's
     * auth_ok before flushing requests/subscriptions. An auth_error is treated
     * as a connection rejection (terminal unless reconnectOnRejected is set).
     * Use refreshAuth() to update the token mid-session without reconnecting.
     */
    getAuthToken?: () => string | Promise<string>;
}

type ResolvedOptions =
    Required<Omit<ApiClientOptions, 'onConnectionRejected' | 'getAuthToken' | 'getConnectParams'>>
    & Pick<ApiClientOptions, 'onConnectionRejected' | 'getAuthToken' | 'getConnectParams'>;

const defaultOptions: ResolvedOptions = {
    transport: 'websocket',
    reconnect: true,
    reconnectInterval: 1000,
    reconnectMaxInterval: 10000,
    reconnectMaxAttempts: 0,
    connectTimeout: 10000,
    reconnectOnRejected: false,
};

/**
 * Appends query parameters to a URL, overriding same-named ones already
 * present and preserving any fragment. String-based rather than URL-based so
 * non-HTTP transport URLs (custom bridges) survive unchanged.
 */
function appendQueryParams(url: string, params: Record<string, string>): string {
    const keys = Object.keys(params);
    if (keys.length === 0) return url;

    const hashAt = url.indexOf('#');
    const fragment = hashAt === -1 ? '' : url.slice(hashAt);
    const withoutFragment = hashAt === -1 ? url : url.slice(0, hashAt);

    const queryAt = withoutFragment.indexOf('?');
    const base = queryAt === -1 ? withoutFragment : withoutFragment.slice(0, queryAt);
    const search = new URLSearchParams(queryAt === -1 ? '' : withoutFragment.slice(queryAt + 1));
    for (const key of keys) search.set(key, params[key]);

    const query = search.toString();
    return query ? `${base}?${query}${fragment}` : `${base}${fragment}`;
}



/**
 * Returns a WebSocket URL based on the current page location.
 * Automatically uses wss: for https: pages and ws: for http: pages.
 * @param path - The WebSocket endpoint path (default: '/ws')
 */
export function getWebSocketUrl(path: string = '/ws'): string {
    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    return `${protocol}//${window.location.host}${path}`;
}

/**
 * Returns an SSE base URL based on the current page location.
 * @param path - The SSE endpoint base path (default: '/sse')
 */
export function getSSEUrl(path: string = '/sse'): string {
    return `${window.location.protocol}//${window.location.host}${path}`;
}



// TransportCloseInfo and ClientTransport are defined in the "types" section
// above. SSE note: the EventSource error event exposes nothing structured,
// so the SSE transport synthesizes an empty close info — it lands as
// 'network-error' after offline/manual checks, which is the most accurate
// bucket browsers will let us name.

class WebSocketTransport implements ClientTransport {
    private ws: WebSocket | null = null;
    private connectTimeout: number;

    constructor(connectTimeoutMs: number = 10000) {
        this.connectTimeout = connectTimeoutMs;
    }

    connect(url: string, onMessage: (data: string | Blob | ArrayBuffer) => void, onClose: (info?: TransportCloseInfo) => void): Promise<void> {
        return new Promise((resolve, reject) => {
            // Detach and close previous socket so its deferred onclose
            // cannot interfere with the new connection (mobile wake race).
            if (this.ws) {
                this.ws.onclose = null;
                this.ws.onerror = null;
                this.ws.onmessage = null;
                this.ws.close();
                this.ws = null;
            }
            let opened = false;
            const ws = new WebSocket(url);
            this.ws = ws;
            // Bound the handshake: a stalled upgrade otherwise holds this
            // promise (and the whole client, which serializes attempts) until
            // the browser's own TCP timeout. Detach handlers before closing so
            // the socket's eventual close event cannot report a second
            // failure for an attempt the client already moved past.
            let timer: ReturnType<typeof setTimeout> | null = null;
            if (this.connectTimeout > 0) {
                timer = setTimeout(() => {
                    ws.onopen = null;
                    ws.onclose = null;
                    ws.onerror = null;
                    ws.onmessage = null;
                    ws.close();
                    if (this.ws === ws) this.ws = null;
                    reject(new Error('WebSocket connect timed out'));
                }, this.connectTimeout);
            }
            ws.binaryType = 'arraybuffer';
            ws.onopen = () => {
                if (timer) clearTimeout(timer);
                opened = true;
                resolve();
            };
            ws.onerror = () => {}; // Error is followed by close
            ws.onmessage = (e) => onMessage(e.data);
            ws.onclose = (event) => {
                if (timer) clearTimeout(timer);
                this.ws = null;
                // Surface the structured CloseEvent so the ApiClient can
                // distinguish a clean post-upgrade close (codes 1000-1015,
                // 4xxx) from a pre-upgrade abnormal closure (1006). The
                // browser deliberately hides upgrade-time HTTP status for
                // fingerprinting reasons, so 1006 is as fine-grained as
                // we get for refused/DNS/TLS/4xx-during-upgrade failures.
                const info: TransportCloseInfo = {
                    code: event.code,
                    reason: event.reason || undefined,
                    wasClean: event.wasClean,
                };
                if (!opened) reject(new Error('WebSocket closed before open'));
                onClose(info);
            };
        });
    }

    send(message: object): void {
        this.ws?.send(JSON.stringify(message));
    }

    disconnect(): void {
        this.ws?.close();
        this.ws = null;
    }

    isConnected(): boolean {
        return this.ws !== null && this.ws.readyState === WebSocket.OPEN;
    }
}

type ClientMessage =
    | { type: 'request'; id: string; method: string; params: unknown[] }
    | { type: 'subscribe'; id: string; method: string; params: unknown[] }
    | { type: 'unsubscribe'; id: string }
    | { type: 'cancel'; id: string }
    | { type: 'auth'; token: string };

class SSETransport implements ClientTransport {
    private eventSource: EventSource | null = null;
    private connectionId: string | null = null;
    private baseUrl: string = '';
    private onMessage: ((data: string) => void) | null = null;
    private connectTimeout: number;

    constructor(connectTimeoutMs: number = 10000) {
        this.connectTimeout = connectTimeoutMs;
    }

    connect(url: string, onMessage: (data: string | Blob | ArrayBuffer) => void, onClose: (info?: TransportCloseInfo) => void): Promise<void> {
        this.baseUrl = url;
        this.onMessage = onMessage;

        return new Promise((resolve, reject) => {
            let connected = false;
            const es = new EventSource(url);
            this.eventSource = es;
            // Bound the handshake, mirroring WebSocketTransport: without it a
            // stream that never delivers 'connected' leaves this promise
            // pending forever and wedges the client's attempt serialization.
            let timer: ReturnType<typeof setTimeout> | null = null;
            if (this.connectTimeout > 0) {
                timer = setTimeout(() => {
                    es.close();
                    if (this.eventSource === es) {
                        this.eventSource = null;
                        this.connectionId = null;
                    }
                    reject(new Error('SSE connect timed out'));
                }, this.connectTimeout);
            }

            es.addEventListener('connected', (e: MessageEvent) => {
                if (timer) clearTimeout(timer);
                connected = true;
                const msg = JSON.parse(e.data);
                this.connectionId = msg.connectionId;
                resolve();
            });

            es.addEventListener('config', (e: MessageEvent) => {
                onMessage(e.data);
            });

            es.addEventListener('auth_ok', (e: MessageEvent) => {
                onMessage(e.data);
            });

            es.addEventListener('auth_error', (e: MessageEvent) => {
                onMessage(e.data);
            });

            es.addEventListener('response', (e: MessageEvent) => {
                onMessage(e.data);
            });

            es.addEventListener('error', (e: MessageEvent) => {
                if (e.data) {
                    onMessage(e.data);
                } else {
                    // EventSource connection error (no data = connectivity issue).
                    // EventSource exposes nothing structured here, so the
                    // ApiClient classifier falls through to 'network-error'
                    // after offline/manual checks.
                    if (timer) clearTimeout(timer);
                    es.close();
                    if (this.eventSource === es) {
                        this.eventSource = null;
                        this.connectionId = null;
                    }
                    // Settle the connect promise on a pre-'connected' failure,
                    // like the WebSocket transport: leaving it pending would
                    // hold the client's in-flight attempt forever.
                    if (!connected) reject(new Error('SSE closed before connected'));
                    onClose({ wasClean: false });
                }
            });

            es.addEventListener('progress', (e: MessageEvent) => {
                onMessage(e.data);
            });

            es.addEventListener('push', (e: MessageEvent) => {
                onMessage(e.data);
            });

            es.addEventListener('stream_item', (e: MessageEvent) => {
                onMessage(e.data);
            });

            es.addEventListener('stream_chunk', (e: MessageEvent) => {
                onMessage(e.data);
            });

            es.addEventListener('stream_end', (e: MessageEvent) => {
                onMessage(e.data);
            });

        });
    }

    send(message: object): void {
        if (!this.connectionId) return;
        const msg = message as ClientMessage;

        if (msg.type === 'auth') {
            // First-message auth rides the POST body (EventSource GET can't set
            // headers). The auth_ok / auth_error result arrives over the stream.
            fetch(this.baseUrl + '/rpc', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    type: 'auth',
                    connectionId: this.connectionId,
                    token: msg.token,
                }),
            }).catch(() => {});
            return;
        }

        if (msg.type === 'request' || msg.type === 'subscribe') {
            fetch(this.baseUrl + '/rpc', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    type: msg.type,
                    connectionId: this.connectionId,
                    id: msg.id,
                    method: msg.method,
                    params: msg.params,
                }),
            }).then((resp) => {
                if (resp.status !== 202) {
                    this.synthesizeError(msg.id, `Server returned unexpected response (status ${resp.status})`);
                }
            }).catch(() => {
                this.synthesizeError(msg.id, 'Network error: failed to send request');
            });
        } else if (msg.type === 'unsubscribe') {
            fetch(this.baseUrl + '/rpc', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    type: 'unsubscribe',
                    connectionId: this.connectionId,
                    id: msg.id,
                }),
            }).catch(() => {});
        } else if (msg.type === 'cancel') {
            fetch(this.baseUrl + '/cancel', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    connectionId: this.connectionId,
                    id: msg.id,
                }),
            }).catch(() => {});
        }
    }

    private synthesizeError(id: string, message: string): void {
        if (this.onMessage) {
            this.onMessage(JSON.stringify({ type: 'error', id, code: -32603, message }));
        }
    }

    disconnect(): void {
        this.eventSource?.close();
        this.eventSource = null;
        this.connectionId = null;
        this.onMessage = null;
    }

    isConnected(): boolean {
        return this.eventSource !== null && this.connectionId !== null;
    }
}

/**
 * url can be a string or a function returning a (possibly async) string.
 * When a function is provided it is called before every connection attempt,
 * allowing the caller to supply a fresh auth token on each reconnect.
 */
export type ApiClientUrl = string | (() => string | Promise<string>);

/**
 * ApiClient never connects automatically. Constructing it (and, in React,
 * mounting <ApiClientProvider>) only configures it — you must call
 * client.connect() once yourself, or no request, hook, or subscription will
 * ever reach the server:
 *
 *     const client = new ApiClient(getWebSocketUrl());
 *     await client.connect();
 *
 * connect() may also be called without awaiting (e.g. at module scope in a
 * React app): it synchronously moves the client into 'connecting', and
 * requests issued while connecting are buffered and flushed once the
 * connection is ready. Requests issued while fully disconnected reject with
 * a ConnectionError. After the first successful connect(), auto-reconnect
 * (when enabled) handles drops, so connect() does not have to be called
 * again — but calling it again is cheap and idempotent: a no-op while
 * connected or connecting, and an immediate attempt otherwise, including
 * while a reconnect backoff is pending. Call it whenever the connection
 * needs to be live (after signing in, on resume) rather than caching an
 * "already connected" flag — such a flag skips the call exactly when the
 * socket has since dropped, and nothing opens a new one.
 */
export class ApiClient {
    private transport: ClientTransport;
    private url: ApiClientUrl;
    private options: ResolvedOptions;
    private requestId = 0;
    private pending = new Map<string, {
        resolve: (value: unknown) => void;
        reject: (error: Error) => void;
        onProgress?: (current: number, total: number, message: string) => void;
        onMessage?: (msg: Record<string, unknown>) => void;
        onSettle?: () => void;
    }>();
    private buffer: Array<{
        method: string;
        params: unknown[];
        options?: RequestOptions;
        resolve: (value: unknown) => void;
        reject: (error: Error) => void;
    }> = [];
    private subscriptions = new Map<string, {
        method: string;
        params: unknown[];
        callback: (data: unknown) => void;
        onError?: (error: Error) => void;
        onPatch?: (patch: unknown) => void;
    }>();
    private streams = new Map<string, {
        push: (item: unknown) => void;
        end: (err: Error | null) => void;
    }>();
    private pushHandlers = new Map<string, Set<(data: unknown) => void>>();
    private stateListeners = new Set<(state: ConnectionState) => void>();
    private loadingListeners = new Set<(count: number) => void>();
    private connectionErrorListeners = new Set<(error: ConnectionError) => void>();
    private requestErrorListeners = new Set<(error: Error, source: ApiClientErrorSource) => void>();
    private lastLoadingCount = 0;
    private state: ConnectionState = 'disconnected';
    private reconnectAttempts = 0;
    private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
    // connectInFlight is the attempt doConnect() is currently running, so a
    // second caller joins it instead of opening a competing socket.
    private connectInFlight: Promise<void> | null = null;
    private manualDisconnect = false;
    // authWaiter resolves/rejects the in-flight auth handshake (initial connect
    // or refreshAuth) when the server's auth_ok / auth_error arrives.
    private authWaiter: { resolve: () => void; reject: (error: Error) => void } | null = null;
    // pendingRejection is set when the server sends a ConnectionRejected
    // ApiError just before tearing down the transport. handleClose() reads
    // it so the resulting ConnectionError carries reason 'server-rejected'
    // (with the original ApiError as cause) rather than the default
    // 'manual' reading triggered by transport.disconnect().
    private pendingRejection: ApiError | null = null;
    // lastRejection outlives pendingRejection: it keeps the ApiError from the
    // most recent rejection until the next successful connect, so a UI can tell
    // "session expired, sign in again" from "server unreachable" even after
    // later transport failures overwrite lastConnectionError.
    private lastRejection: ApiError | null = null;
    // Which connection attempt produced lastRejection. A rejection frame can be
    // delivered in the same event batch that opens the transport, so "clear on
    // success" must not clear a rejection belonging to the very attempt that is
    // completing — compare attempt ids rather than relying on ordering.
    private connectAttemptId = 0;
    private lastRejectionAttemptId = -1;
    // connectParamsFailure is set when the URL function or getConnectParams
    // throws, just before the failure is routed through handleClose(), so
    // classifyClose() can name the reason and attach the thrown error as
    // cause. Wrapped in an object so a thrown null/undefined still counts.
    // Consumed by handleClose(), exactly like pendingRejection.
    private connectParamsFailure: { cause: unknown } | null = null;
    // lastConnectionError is the most recently observed ConnectionError,
    // exposed via getLastConnectionError() so a UI can render an offline
    // banner / "server unreachable" message after the fact.
    private lastConnectionError: ConnectionError | null = null;
    // Normalized reconnectOnRejected policy; null when rejection is terminal.
    private rejectionRetry: { delayMs: number; maxAttempts: number } | null = null;
    private rejectionRetryAttempts = 0;
    private visibilityHandler: (() => void) | null = null;
    private onlineHandler: (() => void) | null = null;

    constructor(url: ApiClientUrl, options?: ApiClientOptions) {
        this.url = url;
        this.options = { ...defaultOptions, ...options };
        this.transport = typeof this.options.transport === 'object'
            ? this.options.transport
            : this.options.transport === 'sse'
                ? new SSETransport(this.options.connectTimeout)
                : new WebSocketTransport(this.options.connectTimeout);

        const retry = this.options.reconnectOnRejected;
        if (retry) {
            const cfg = retry === true ? {} : retry;
            this.rejectionRetry = {
                delayMs: cfg.delayMs ?? 2000,
                maxAttempts: cfg.maxAttempts ?? 0,
            };
        }
    }

    /**
     * Opens the connection to the server. This is a required manual step:
     * it is never called automatically — not by the constructor, not by
     * <ApiClientProvider>, not by the generated hooks/functions.
     *
     * It is cheap and idempotent, so call it whenever the connection needs to
     * be live (after signing in, on resume) rather than remembering that it
     * was called: it is a no-op while connected or connecting, and otherwise
     * attempts a connection immediately — including while a reconnect backoff
     * is pending, in which case the backoff is abandoned rather than waited
     * out. Auto-reconnect takes over after the first successful call.
     */
    connect(): Promise<void> {
        if (this.state === 'connected' || this.state === 'connecting') {
            return Promise.resolve();
        }
        return this.startConnect();
    }

    /**
     * Abandons any pending reconnect backoff and attempts a connection now,
     * keeping subscriptions and in-flight requests — unlike disconnect() +
     * connect(), which clears both.
     *
     * connect() already does this, so reach for reconnectNow() only when the
     * client may be in a state connect() reads as "nothing to do": a socket
     * the runtime left half-open still reports 'connected' until its close
     * event lands. Resolves when the attempt finishes, connected or not, and
     * joins an attempt already in flight rather than starting a second one.
     */
    reconnectNow(): Promise<void> {
        return this.startConnect();
    }

    // startConnect is the manual-connect path behind connect() and
    // reconnectNow(): a fresh start followed by an immediate attempt.
    private startConnect(): Promise<void> {
        this.manualDisconnect = false;
        // A manual connect is a fresh start: un-park a client that exhausted
        // its rejection retries, and restart the backoff schedule.
        this.rejectionRetryAttempts = 0;
        this.reconnectAttempts = 0;
        // Drop a pending backoff. The caller wants a connection now, and a
        // timer left armed would fire a second doConnect() on top of the
        // connection this call is about to establish.
        this.clearReconnectTimer();
        this.setupPageListeners();
        return this.doConnect();
    }

    // doConnect serializes connection attempts: at most one runs at a time,
    // and a live socket is never replaced. Both matter because the transports
    // detach the previous socket's handlers before opening a new one, so the
    // replaced socket's close is never reported and anything waiting on it
    // would hang forever.
    private doConnect(): Promise<void> {
        if (this.state === 'connected' && this.transport.isConnected()) {
            return Promise.resolve();
        }
        if (this.connectInFlight) return this.connectInFlight;
        const attempt = this.runConnect().finally(() => {
            if (this.connectInFlight === attempt) this.connectInFlight = null;
        });
        this.connectInFlight = attempt;
        return attempt;
    }

    private async runConnect(): Promise<void> {
        // Reached with state 'connected' only when the transport disagrees:
        // the socket is half-open or already torn down (mobile wake). It is
        // about to be replaced, and its handlers are detached in the process,
        // so handleClose() will never run for it — settle whatever is bound to
        // it here, or those promises never settle at all.
        if (this.state === 'connected') {
            this.abandonInFlight();
        }
        const attemptId = ++this.connectAttemptId;
        this.setState(this.reconnectAttempts > 0 ? 'reconnecting' : 'connecting');

        // The URL function and getConnectParams are both resolved per attempt,
        // so every reconnect can carry a freshly minted short-lived token. A
        // failure here is treated like a transport failure rather than left to
        // reject doConnect()'s promise, which callers ignore — that would
        // silently halt reconnection.
        let url: string;
        try {
            url = typeof this.url === 'function' ? await this.url() : this.url;
            if (this.options.getConnectParams) {
                url = appendQueryParams(url, await this.options.getConnectParams());
            }
        } catch (err) {
            this.connectParamsFailure = { cause: err };
            this.handleClose({ wasClean: false });
            return;
        }

        return this.transport.connect(
            url,
            (data) => this.handleMessage(data),
            (info) => this.handleClose(info),
        ).then(async () => {
            this.reconnectAttempts = 0;
            // First-message auth: authenticate before the connection is
            // considered ready, so buffered requests/subscriptions only flush
            // after auth_ok. Runs again automatically on every reconnect.
            if (this.options.getAuthToken) {
                try {
                    await this.authenticate();
                } catch (err) {
                    // The server rejected the token: classify like a connection
                    // rejection (no auto-reconnect), carrying the auth error.
                    const apiError = err instanceof ApiError
                        ? err
                        : new ApiError(ErrorCode.AuthFailed, 'authentication failed');
                    this.manualDisconnect = true;
                    this.pendingRejection = apiError;
                    this.lastRejection = apiError;
                    this.lastRejectionAttemptId = attemptId;
                    this.options.onConnectionRejected?.(apiError);
                    this.transport.disconnect();
                    return;
                }
            }
            // The connection is usable: forget why the *previous* one ended,
            // unless this very attempt was already rejected in the same event
            // batch. The retry streak is deliberately not reset here — an
            // in-band rejection also passes through this point, so resetting
            // would clear the streak on every attempt; handleClose() does it.
            if (this.lastRejectionAttemptId !== attemptId) {
                this.lastRejection = null;
            }
            this.setState('connected');
        }).catch(() => {
            // The transport's promise rejected before opening — treat as a
            // pre-upgrade close with no diagnostic info available.
            this.handleClose({ wasClean: false });
        });
    }

    // authenticate resolves the token via getAuthToken, sends the auth frame,
    // and resolves on auth_ok / rejects on auth_error (handled in handleMessage).
    private authenticate(): Promise<void> {
        return new Promise<void>((resolve, reject) => {
            // A newer handshake supersedes any in-flight one.
            this.authWaiter?.reject(new Error('superseded by a newer auth'));
            this.authWaiter = { resolve, reject };
            Promise.resolve(this.options.getAuthToken!())
                .then((token) => this.transport.send({ type: 'auth', token }))
                .catch((e) => {
                    if (this.authWaiter?.reject === reject) this.authWaiter = null;
                    reject(e instanceof Error ? e : new Error(String(e)));
                });
        });
    }

    /**
     * Refresh the auth token on the live connection without reconnecting. Sends
     * an auth frame with the given token (or getAuthToken() when omitted) and
     * resolves on auth_ok. On auth_error the promise rejects but the existing
     * session is kept — the server does not downgrade a live connection.
     */
    async refreshAuth(token?: string): Promise<void> {
        let t = token;
        if (t === undefined) {
            if (!this.options.getAuthToken) {
                throw new Error('refreshAuth requires a token argument or a getAuthToken option');
            }
            t = await this.options.getAuthToken();
        }
        return new Promise<void>((resolve, reject) => {
            this.authWaiter?.reject(new Error('superseded by a newer auth'));
            this.authWaiter = { resolve, reject };
            this.transport.send({ type: 'auth', token: t as string });
        });
    }

    // classifyClose decides why the transport closed. Order matters:
    //   1. Server-rejected wins because the server explicitly told us why
    //      (we keep the ApiError as `cause`).
    //   2. Manual disconnect comes next — the caller initiated the close.
    //   3. Offline overrides everything else; navigator.onLine being false
    //      means even a clean close happened during a network outage and
    //      "offline" is the more useful message — including when it was the
    //      URL/params callback that failed, since it failed *because* the
    //      network is down.
    //   4. A URL function / getConnectParams throw is named before the
    //      transport buckets: no socket was ever involved, so close-code
    //      reasoning does not apply.
    //   5. A close code outside the abnormal range (1006) and 0 means the
    //      WebSocket upgrade succeeded and the server closed cleanly.
    //   6. Otherwise the failure happened before/at upgrade time and the
    //      browser collapses every cause into an indistinguishable
    //      'network-error'.
    private classifyClose(info?: TransportCloseInfo): ConnectionErrorReason {
        if (this.pendingRejection || info?.serverRejected) {
            return 'server-rejected';
        }
        if (this.manualDisconnect) return 'manual';
        if (typeof navigator !== 'undefined' && navigator.onLine === false) {
            return 'offline';
        }
        if (this.connectParamsFailure) return 'connect-params-failed';
        if (info?.code !== undefined && info.code !== 1006 && info.code !== 0) {
            return 'server-closed';
        }
        return 'network-error';
    }

    private buildConnectionError(reason: ConnectionErrorReason, info?: TransportCloseInfo): ConnectionError {
        let message: string;
        const init: ConnectionErrorInit = {
            closeCode: info?.code,
            closeReason: info?.reason,
        };
        switch (reason) {
            case 'offline':
                message = 'Offline: no network connection';
                break;
            case 'server-rejected': {
                const cause = this.pendingRejection;
                init.cause = cause ?? undefined;
                message = cause?.message
                    ? `Server rejected connection: ${cause.message}`
                    : 'Server rejected connection';
                break;
            }
            case 'server-closed':
                message = info?.reason
                    ? `Server closed connection (code ${info.code}): ${info.reason}`
                    : `Server closed connection (code ${info?.code ?? 'unknown'})`;
                break;
            case 'network-error':
                message = 'Network error: connection lost';
                break;
            case 'connect-params-failed': {
                const cause = this.connectParamsFailure?.cause;
                init.cause = cause;
                message = cause instanceof Error && cause.message
                    ? `Failed to resolve connection URL or params: ${cause.message}`
                    : 'Failed to resolve connection URL or params';
                break;
            }
            case 'manual':
                message = 'Disconnected';
                break;
        }
        return new ConnectionError(reason, message, init);
    }

    /**
     * onRequestError observes every failed call this client makes: a rejected
     * request, a subscription error, or a stream that throws. The listener
     * receives the error and which generated call produced it.
     *
     * Reported by the client itself rather than by a wrapper around it, so a
     * caller cannot avoid it by holding the client some other way. A module
     * that imports the client directly, outside React, reports exactly as a
     * component does.
     *
     * The error is still thrown/surfaced to the caller afterwards, so
     * per-call try/catch and per-hook error fields keep working. This is an
     * observer, not a handler.
     *
     * Returns an unsubscribe function. Multiple listeners are supported.
     */
    onRequestError(listener: (error: Error, source: ApiClientErrorSource) => void): () => void {
        this.requestErrorListeners.add(listener);
        return () => this.requestErrorListeners.delete(listener);
    }

    private notifyRequestError(error: Error, source: ApiClientErrorSource): void {
        for (const listener of this.requestErrorListeners) {
            listener(error, source);
        }
    }

    private notifyConnectionError(error: ConnectionError): void {
        this.lastConnectionError = error;
        for (const listener of this.connectionErrorListeners) {
            listener(error);
        }
    }

    private handleClose(info?: TransportCloseInfo): void {
        // disconnect() rejects pending requests/streams synchronously and
        // sets state to 'disconnected'. The transport's onclose still fires
        // afterwards to confirm the close — short-circuit so we don't
        // re-notify listeners or rebuild the error.
        if (this.manualDisconnect && this.state === 'disconnected') {
            this.pendingRejection = null;
            this.connectParamsFailure = null;
            return;
        }
        const reason = this.classifyClose(info);
        const error = this.buildConnectionError(reason, info);
        // Consume the pending rejection and params failure: subsequent
        // reconnect attempts (e.g. after the auth flow refreshes) must not
        // be misclassified.
        this.pendingRejection = null;
        this.connectParamsFailure = null;

        // Reject all pending requests (but keep subscription entries for reconnect)
        const subIds = new Set(this.subscriptions.keys());
        for (const [id, p] of this.pending) {
            if (!subIds.has(id)) {
                p.onSettle?.();
                p.reject(error);
            }
            this.pending.delete(id);
        }
        // End all in-flight streams with the structured connection error.
        // Streams are not auto-resumed on reconnect; consumers must restart
        // them.
        const streams = Array.from(this.streams.values());
        this.streams.clear();
        for (const s of streams) {
            s.end(error);
        }
        this.notifyLoadingChange();
        this.notifyConnectionError(error);

        // reconnectOnRejected bounds *consecutive* rejections: any other kind
        // of close ends the streak, so a session that dropped for unrelated
        // reasons starts its retry budget fresh.
        if (reason !== 'server-rejected') {
            this.rejectionRetryAttempts = 0;
        }

        if (this.manualDisconnect) {
            // A rejection sets manualDisconnect to stop auto-reconnect. With
            // reconnectOnRejected the rejection is retryable instead: clear the
            // flag so the next attempt is classified normally, and retry until
            // maxAttempts is reached (then park as before).
            if (
                reason === 'server-rejected' && this.rejectionRetry && (
                    this.rejectionRetry.maxAttempts === 0 ||
                    this.rejectionRetryAttempts < this.rejectionRetry.maxAttempts
                )
            ) {
                this.manualDisconnect = false;
                this.scheduleRejectionRetry();
                return;
            }
            this.setState('disconnected');
            return;
        }

        // Auto-reconnect if enabled
        if (this.options.reconnect && (
            this.options.reconnectMaxAttempts === 0 ||
            this.reconnectAttempts < this.options.reconnectMaxAttempts
        )) {
            this.scheduleReconnect();
        } else {
            this.setState('disconnected');
        }
    }

    // abandonInFlight settles everything bound to a socket that is being
    // replaced rather than closed. Subscription entries are kept: they are
    // re-established on the new connection, exactly as after handleClose().
    private abandonInFlight(): void {
        if (this.pending.size === 0 && this.streams.size === 0) return;
        const info: TransportCloseInfo = { wasClean: false };
        const error = this.buildConnectionError(this.classifyClose(info), info);
        const subIds = new Set(this.subscriptions.keys());
        for (const [id, p] of this.pending) {
            if (!subIds.has(id)) {
                p.onSettle?.();
                p.reject(error);
            }
            this.pending.delete(id);
        }
        const streams = Array.from(this.streams.values());
        this.streams.clear();
        for (const s of streams) {
            s.end(error);
        }
        this.notifyLoadingChange();
        this.notifyConnectionError(error);
    }

    private clearReconnectTimer(): void {
        if (this.reconnectTimer) {
            clearTimeout(this.reconnectTimer);
            this.reconnectTimer = null;
        }
    }

    private scheduleReconnect(): void {
        if (this.reconnectTimer) return;

        // Linear backoff: attempt n waits n × reconnectInterval, capped at
        // reconnectMaxInterval — 1s, 2s, 3s, … 10s with the defaults. Chosen
        // over exponential deliberately: a failure streak (e.g. a token
        // provider outage) otherwise escalates to a max-interval wait that
        // stalls the next successful connect far longer than it saves.
        const delay = Math.min(
            this.options.reconnectInterval * (this.reconnectAttempts + 1),
            this.options.reconnectMaxInterval
        );
        this.reconnectAttempts++;
        this.setState('reconnecting');

        this.reconnectTimer = setTimeout(() => {
            this.reconnectTimer = null;
            this.doConnect().catch(() => {
                // Error handled in handleClose
            });
        }, delay);
    }

    // scheduleRejectionRetry re-attempts a connection the server rejected, when
    // reconnectOnRejected is enabled. The delay is fixed rather than backed off:
    // a rejection means the server is reachable and answered, so this is not
    // congestion — it is a credential that should be fresh on the next attempt.
    // It deliberately shares reconnectTimer, so disconnect() and page-wake
    // already cancel a pending retry.
    private scheduleRejectionRetry(): void {
        if (this.reconnectTimer) return;

        this.rejectionRetryAttempts++;
        this.setState('reconnecting');

        this.reconnectTimer = setTimeout(() => {
            this.reconnectTimer = null;
            this.doConnect().catch(() => {
                // Error handled in handleClose
            });
        }, this.rejectionRetry!.delayMs);
    }

    disconnect(): void {
        if (this.manualDisconnect) return;
        this.manualDisconnect = true;
        this.teardownPageListeners();
        this.clearReconnectTimer();
        this.subscriptions.clear();

        // Reject in-flight requests/streams synchronously: the server may
        // still respond between transport.disconnect() and the close event
        // landing, racing the rejection in handleClose() and resolving the
        // promise instead. Doing it here means the caller's "I'm done"
        // semantics win over a late server reply.
        const error = this.buildConnectionError('manual', undefined);
        for (const [, p] of this.pending) {
            p.onSettle?.();
            p.reject(error);
        }
        this.pending.clear();
        const streams = Array.from(this.streams.values());
        this.streams.clear();
        for (const s of streams) {
            s.end(error);
        }
        this.notifyLoadingChange();
        this.notifyConnectionError(error);

        this.transport.disconnect();
        this.setState('disconnected');
    }

    getState(): ConnectionState {
        return this.state;
    }

    private setState(state: ConnectionState): void {
        if (this.state === state) return;
        this.state = state;
        if (state === 'connected') {
            this.flushBuffer();
            this.resubscribeAll();
        } else if (state === 'disconnected') {
            // Reuse the most recent classified error if handleClose() just
            // ran, so a request buffered during a reconnect attempt that
            // ultimately fails is rejected with the same reason as the
            // close itself (e.g. 'offline'). Falls back to 'manual' when
            // there's no prior error — that branch is hit by an idle
            // disconnect() with no in-flight close.
            const err = this.lastConnectionError ?? new ConnectionError('manual', 'Not connected');
            this.rejectBuffer(err);
        }
        for (const listener of this.stateListeners) {
            listener(state);
        }
    }

    onStateChange(listener: (state: ConnectionState) => void): () => void {
        this.stateListeners.add(listener);
        return () => this.stateListeners.delete(listener);
    }

    onLoadingChange(listener: (count: number) => void): () => void {
        this.loadingListeners.add(listener);
        return () => this.loadingListeners.delete(listener);
    }

    /**
     * onConnectionError registers a listener that fires every time a
     * connection-level failure is classified (transport close, server
     * rejection, etc.). The listener receives a structured ConnectionError
     * carrying the reason and any close-event diagnostics the browser
     * exposed. Use this to drive UI like an "Offline" banner.
     *
     * Returns an unsubscribe function. Multiple listeners are supported.
     */
    onConnectionError(listener: (error: ConnectionError) => void): () => void {
        this.connectionErrorListeners.add(listener);
        return () => this.connectionErrorListeners.delete(listener);
    }

    /**
     * getLastConnectionError returns the most recent ConnectionError, or
     * null if no failure has been observed (or the connection has never
     * dropped). Useful right after `getState() === 'disconnected'` or
     * 'reconnecting' to decide what message to show the user.
     */
    getLastConnectionError(): ConnectionError | null {
        return this.lastConnectionError;
    }

    /**
     * getLastRejection returns the ApiError from the most recent connection
     * rejection — a server rejection (e.g. invalid session) or a failed
     * first-message auth — or null if none has occurred since the last
     * successful connect. Use it to tell "signed out / session expired" from
     * "server unreachable": unlike getLastConnectionError(), it is not
     * overwritten by later transport failures, so it survives retries and
     * still explains why the session ended. Cleared on the next successful
     * connect.
     */
    getLastRejection(): ApiError | null {
        return this.lastRejection;
    }

    getLoadingCount(): number {
        let count = this.buffer.length + this.streams.size;
        for (const id of this.pending.keys()) {
            if (!this.subscriptions.has(id)) count++;
        }
        return count;
    }

    isConnected(): boolean {
        return this.state === 'connected';
    }

    private setupPageListeners(): void {
        if (typeof document === 'undefined') return;
        this.teardownPageListeners();

        this.visibilityHandler = () => {
            if (!document.hidden) this.handlePageWake();
        };
        this.onlineHandler = () => this.handlePageWake();

        document.addEventListener('visibilitychange', this.visibilityHandler);
        window.addEventListener('online', this.onlineHandler);
    }

    private teardownPageListeners(): void {
        if (typeof document === 'undefined') return;
        if (this.visibilityHandler) {
            document.removeEventListener('visibilitychange', this.visibilityHandler);
            this.visibilityHandler = null;
        }
        if (this.onlineHandler) {
            window.removeEventListener('online', this.onlineHandler);
            this.onlineHandler = null;
        }
    }

    private handlePageWake(): void {
        if (this.manualDisconnect) return;
        if (this.state === 'connected' && this.transport.isConnected()) return;
        if (this.state === 'connecting') return;

        this.clearReconnectTimer();
        this.reconnectAttempts = 0;
        this.doConnect().catch(() => {});
    }

    private notifyLoadingChange(): void {
        // Read through getLoadingCount() so the listener-facing count and the
        // public getter cannot diverge. Subscription pending entries (added
        // by subscribe() and re-added by resubscribeAll() on reconnect) must
        // not flip useIsLoading() to true — otherwise reconnects after auth
        // refresh or coming back from another app leave the global loading
        // state stuck until every subscription's first response arrives.
        const count = this.getLoadingCount();
        if (count !== this.lastLoadingCount) {
            this.lastLoadingCount = count;
            for (const listener of this.loadingListeners) {
                listener(count);
            }
        }
    }

    private handleMessage(data: string | Blob | ArrayBuffer): void {
        if (typeof data !== 'string') {
            this.handleBinaryMessage(data);
            return;
        }
        const msg = JSON.parse(data);
        switch (msg.type) {
            case 'config':
                this.applyConfig(msg);
                break;
            case 'auth_ok': {
                const waiter = this.authWaiter;
                this.authWaiter = null;
                waiter?.resolve();
                break;
            }
            case 'auth_error': {
                const waiter = this.authWaiter;
                this.authWaiter = null;
                waiter?.reject(new ApiError(ErrorCode.AuthFailed, msg.message ?? 'authentication failed'));
                break;
            }
            case 'response': {
                this.settleResponse(msg.id, decodeBlobResult(msg.result));
                break;
            }
            case 'subscription_patch': {
                const sub = this.subscriptions.get(msg.id);
                if (!sub) break;
                if (sub.onPatch) {
                    sub.onPatch(msg.patch);
                } else if (this.transport.isConnected()) {
                    // Defensive: the server only sends patches to subscriptions
                    // that declared support, so this should not happen — but if
                    // it does, re-subscribe to fetch the full result rather
                    // than silently going stale.
                    this.transport.send({ type: 'subscribe', id: msg.id, method: sub.method, params: sub.params });
                }
                break;
            }
            case 'error': {
                const p = this.pending.get(msg.id);
                if (p) {
                    this.pending.delete(msg.id);
                    p.onSettle?.();
                    p.reject(new ApiError(msg.code, msg.message, msg.data));
                    this.notifyLoadingChange();
                    break;
                }
                // Preflight errors from a streaming handler arrive as a
                // regular `error` envelope (not `stream_end`). Terminate the
                // stream with the error so the for-await loop throws.
                const stream = this.streams.get(msg.id);
                if (stream) {
                    this.streams.delete(msg.id);
                    stream.end(new ApiError(msg.code, msg.message, msg.data));
                    this.notifyLoadingChange();
                    break;
                }
                if (msg.code === ErrorCode.ConnectionRejected) {
                    const apiError = new ApiError(msg.code, msg.message, msg.data);
                    this.manualDisconnect = true;
                    // Stash the rejection so the imminent transport close
                    // is classified as 'server-rejected' rather than the
                    // default 'manual' that manualDisconnect=true would
                    // otherwise produce. handleClose() consumes it.
                    this.pendingRejection = apiError;
                    this.lastRejection = apiError;
                    this.lastRejectionAttemptId = this.connectAttemptId;
                    this.options.onConnectionRejected?.(apiError);
                    this.transport.disconnect();
                } else {
                    // Server-driven subscription refresh error
                    const sub = this.subscriptions.get(msg.id);
                    if (sub) {
                        sub.onError?.(new ApiError(msg.code, msg.message, msg.data));
                    }
                }
                break;
            }
            case 'progress': {
                const p = this.pending.get(msg.id);
                if (p) {
                    if (p.onProgress && (msg.current != null || msg.total != null || msg.message)) {
                        p.onProgress(msg.current ?? 0, msg.total ?? 0, msg.message ?? '');
                    }
                    p.onMessage?.(msg);
                }
                break;
            }
            case 'push': {
                const handlers = this.pushHandlers.get(msg.event);
                if (handlers) {
                    for (const handler of handlers) {
                        handler(msg.data);
                    }
                }
                break;
            }
            case 'stream_item': {
                const s = this.streams.get(msg.id);
                if (s) s.push(msg.item);
                break;
            }
            case 'stream_chunk': {
                // Server-side chunking (ServerOptions.StreamChunking) batches
                // consecutive items into one frame; unroll so the
                // AsyncIterable still yields one item at a time.
                const s = this.streams.get(msg.id);
                if (s && Array.isArray(msg.items)) {
                    for (const item of msg.items) s.push(item);
                }
                break;
            }
            case 'stream_end': {
                const s = this.streams.get(msg.id);
                if (s) {
                    this.streams.delete(msg.id);
                    if (msg.code) {
                        s.end(new ApiError(msg.code, msg.message, msg.data));
                    } else {
                        s.end(null);
                    }
                    this.notifyLoadingChange();
                }
                break;
            }
        }
    }

    /**
     * Delivers a result for `id`: settles the pending request if there is
     * one, otherwise dispatches to the matching server-driven subscription.
     * Both the JSON `response` envelope and binary frames end here, so the
     * two paths cannot drift apart.
     */
    private settleResponse(id: string, result: unknown): void {
        const p = this.pending.get(id);
        if (p) {
            this.pending.delete(id);
            p.onSettle?.();
            p.resolve(result);
            this.notifyLoadingChange();
        } else {
            // Server-driven subscription refresh
            const sub = this.subscriptions.get(id);
            if (sub) {
                sub.callback(result);
            }
        }
    }

    private rejectResponse(id: string, error: Error): void {
        const p = this.pending.get(id);
        if (p) {
            this.pending.delete(id);
            p.onSettle?.();
            p.reject(error);
            this.notifyLoadingChange();
        } else {
            const sub = this.subscriptions.get(id);
            if (sub) {
                sub.onError?.(error);
            }
        }
    }

    private async handleBinaryMessage(data: Blob | ArrayBuffer): Promise<void> {
        const buffer = data instanceof ArrayBuffer ? data : await data.arrayBuffer();
        const view = new DataView(buffer);
        const headerLen = view.getUint32(0, false);
        const headerBytes = new Uint8Array(buffer, 4, headerLen);
        const header = JSON.parse(binaryHeaderDecoder.decode(headerBytes));
        if (header.version !== 1 || header.type !== 'response') {
            // Unknown frame: reject rather than drop, so the awaiting caller
            // fails fast instead of hanging until the connection closes.
            this.rejectResponse(header.id, new ApiError(
                ErrorCode.InternalError,
                `unsupported binary frame (version ${header.version}, type ${header.type})`,
            ));
            return;
        }
        // Zero-copy view into the received buffer; Blob copies on read.
        const payload = new Uint8Array(buffer, 4 + headerLen);
        const blob = new Blob([payload], header.contentType ? { type: header.contentType } : undefined);
        this.settleResponse(header.id, blob);
    }

    private applyConfig(config: {
        reconnectInterval?: number;
        reconnectMaxInterval?: number;
        reconnectMaxAttempts?: number;
    }): void {
        if (config.reconnectInterval !== undefined) {
            this.options.reconnectInterval = config.reconnectInterval;
        }
        if (config.reconnectMaxInterval !== undefined) {
            this.options.reconnectMaxInterval = config.reconnectMaxInterval;
        }
        if (config.reconnectMaxAttempts !== undefined) {
            this.options.reconnectMaxAttempts = config.reconnectMaxAttempts;
        }
    }

    request<T>(method: string, params: unknown[], options?: RequestOptions): Promise<T> {
        return this.requestInner<T>(method, params, options).catch((err: unknown) => {
            if (err instanceof Error) this.notifyRequestError(err, parseMethodSource(method));
            throw err;
        });
    }

    private requestInner<T>(method: string, params: unknown[], options?: RequestOptions): Promise<T> {
        return new Promise((resolve, reject) => {
            const res = resolve as (value: unknown) => void;
            if (this.transport.isConnected()) {
                this.sendRequest(method, params, options, res, reject);
                return;
            }
            if (this.state === 'connecting' || this.state === 'reconnecting') {
                const entry = { method, params, options, resolve: res, reject };
                this.buffer.push(entry);
                this.notifyLoadingChange();
                if (options?.signal) {
                    if (options.signal.aborted) {
                        this.buffer.pop();
                        reject(new Error('Request aborted'));
                        this.notifyLoadingChange();
                        return;
                    }
                    options.signal.addEventListener('abort', () => {
                        const idx = this.buffer.indexOf(entry);
                        if (idx !== -1) {
                            this.buffer.splice(idx, 1);
                            reject(new Error('Request aborted'));
                            this.notifyLoadingChange();
                        }
                    }, { once: true });
                }
                return;
            }
            // Disconnected and not reconnecting. Prefer the most recent
            // ConnectionError (set by handleClose) so callers see the same
            // reason that classified the transport drop. If we got here
            // without a prior failure (e.g. caller never connected, or
            // navigator.onLine flipped between connect and request), still
            // surface a ConnectionError with the best reason we can name.
            let err = this.lastConnectionError;
            if (!err) {
                if (typeof navigator !== 'undefined' && navigator.onLine === false) {
                    err = new ConnectionError('offline', 'Offline: no network connection');
                } else {
                    err = new ConnectionError('manual', 'Not connected: call client.connect() first — the client never connects automatically');
                }
            }
            reject(err);
        });
    }

    private sendRequest(method: string, params: unknown[], options: RequestOptions | undefined,
        resolve: (value: unknown) => void, reject: (error: Error) => void): void {
        const id = String(++this.requestId);
        const onSettle = options?._onSettle;
        this.pending.set(id, {
            resolve, reject,
            onProgress: options?.onProgress,
            onMessage: options?.onMessage,
            onSettle,
        });
        options?._onStart?.(id);
        if (options?.signal) {
            if (options.signal.aborted) {
                this.pending.delete(id);
                onSettle?.();
                reject(new Error('Request aborted'));
                this.notifyLoadingChange();
                return;
            }
            options.signal.addEventListener('abort', () => {
                const p = this.pending.get(id);
                if (p) {
                    this.pending.delete(id);
                    p.onSettle?.();
                }
                this.transport.send({ type: 'cancel', id });
                reject(new Error('Request aborted'));
                this.notifyLoadingChange();
            }, { once: true });
        }
        this.transport.send({ type: 'request', id, method, params });
        this.notifyLoadingChange();
    }

    private flushBuffer(): void {
        const buffered = this.buffer;
        this.buffer = [];
        for (const entry of buffered) {
            if (entry.options?.signal?.aborted) {
                entry.reject(new Error('Request aborted'));
                this.notifyLoadingChange();
                continue;
            }
            this.sendRequest(entry.method, entry.params, entry.options, entry.resolve, entry.reject);
        }
    }

    private rejectBuffer(error: Error): void {
        const buffered = this.buffer;
        this.buffer = [];
        for (const entry of buffered) {
            entry.reject(error);
        }
        this.notifyLoadingChange();
    }

    private resubscribeAll(): void {
        for (const [id, sub] of this.subscriptions) {
            this.pending.set(id, {
                resolve: (result) => { sub.callback(result); },
                reject: (err) => { sub.onError?.(err as Error); },
            });
            this.transport.send({ type: 'subscribe', id, method: sub.method, params: sub.params, ...(sub.onPatch ? { patch: true } : {}) });
        }
        this.notifyLoadingChange();
    }

    onPush<T>(event: string, handler: PushHandler<T>): () => void {
        if (!this.pushHandlers.has(event)) {
            this.pushHandlers.set(event, new Set());
        }
        const cb = handler as (data: unknown) => void;
        this.pushHandlers.get(event)!.add(cb);
        return () => {
            this.pushHandlers.get(event)?.delete(cb);
        };
    }

    subscribe<T>(method: string, params: unknown[], callback: (data: T) => void, onError?: (error: Error) => void, options?: SubscribeOptions): () => void {
        const subscribeSource = parseMethodSource(method);
        const callerOnError = onError;
        onError = (error: Error) => {
            this.notifyRequestError(error, subscribeSource);
            callerOnError?.(error);
        };
        const id = String(++this.requestId);
        const cb = callback as (data: unknown) => void;
        const onPatch = options?.onPatch;
        this.subscriptions.set(id, { method, params, callback: cb, onError, onPatch });

        // Register in pending for the initial response
        this.pending.set(id, {
            resolve: (result) => { cb(result); },
            reject: (err) => { onError?.(err as Error); },
        });

        if (this.transport.isConnected()) {
            this.transport.send({ type: 'subscribe', id, method, params, ...(onPatch ? { patch: true } : {}) });
        }

        return () => {
            this.subscriptions.delete(id);
            this.pending.delete(id);
            if (this.transport.isConnected()) {
                this.transport.send({ type: 'unsubscribe', id });
            }
        };
    }

    /**
     * Opens a server-side streaming request and returns an AsyncIterable that
     * yields items as they arrive. Each call to `[Symbol.asyncIterator]()`
     * starts a fresh server request — the returned iterable is a factory,
     * not a singleton.
     *
     * Use with `for await`:
     * ```ts
     * for await (const user of streamUsers(client)) { ... }
     * ```
     *
     * Cancellation: breaking out of the `for await` loop, calling `.return()`
     * on the iterator, or aborting via `options.signal` sends a `cancel`
     * message to the server. Streams in flight at disconnect time are
     * rejected with an error and are NOT auto-resumed on reconnect.
     */
    requestStream<T>(method: string, params: unknown[], options?: RequestOptions): AsyncIterable<T> {
        const inner = this.requestStreamInner<T>(method, params, options);
        const source = parseMethodSource(method);
        return {
            [Symbol.asyncIterator]: (): AsyncIterator<T> => {
                const it = inner[Symbol.asyncIterator]();
                return {
                    next: (...args) => it.next(...args).catch((err: unknown) => {
                        if (err instanceof Error) this.notifyRequestError(err, source);
                        throw err;
                    }),
                    return: it.return ? it.return.bind(it) : undefined,
                    throw: it.throw ? it.throw.bind(it) : undefined,
                };
            },
        };
    }

    private requestStreamInner<T>(method: string, params: unknown[], options?: RequestOptions): AsyncIterable<T> {
        // Arrow factory captures `this` lexically — avoids aliasing `this` to a
        // local variable (which trips @typescript-eslint/no-this-alias under
        // strict presets). All inner closures are also arrows, so they inherit
        // the same `this` (the ApiClient instance).
        return {
            [Symbol.asyncIterator]: (): AsyncIterator<T> => {
                let id = '';
                let started = false;
                const buffer: T[] = [];
                const waiters: Array<{
                    resolve: (r: IteratorResult<T>) => void;
                    reject: (e: Error) => void;
                }> = [];
                let ended = false;
                let endError: Error | null = null;

                const push = (item: unknown) => {
                    if (ended) return;
                    const w = waiters.shift();
                    if (w) {
                        w.resolve({ value: item as T, done: false });
                    } else {
                        buffer.push(item as T);
                    }
                };
                const end = (err: Error | null) => {
                    if (ended) return;
                    ended = true;
                    endError = err;
                    const pending = waiters.splice(0);
                    for (const w of pending) {
                        if (err) {
                            w.reject(err);
                        } else {
                            w.resolve({ value: undefined as unknown as T, done: true });
                        }
                    }
                };

                const cancelAtServer = () => {
                    if (id && !ended) {
                        this.streams.delete(id);
                        if (this.transport.isConnected()) {
                            this.transport.send({ type: 'cancel', id });
                        }
                    }
                };

                const ensureStarted = () => {
                    if (started) return;
                    started = true;
                    if (!this.transport.isConnected()) {
                        const err = this.lastConnectionError ?? (
                            typeof navigator !== 'undefined' && navigator.onLine === false
                                ? new ConnectionError('offline', 'Offline: no network connection')
                                : new ConnectionError('manual', 'Not connected: call client.connect() first — the client never connects automatically')
                        );
                        end(err);
                        return;
                    }
                    id = String(++this.requestId);
                    this.streams.set(id, { push, end });
                    this.notifyLoadingChange();
                    if (options?.signal) {
                        if (options.signal.aborted) {
                            cancelAtServer();
                            end(new Error('Request aborted'));
                            return;
                        }
                        options.signal.addEventListener('abort', () => {
                            cancelAtServer();
                            end(new Error('Request aborted'));
                        }, { once: true });
                    }
                    this.transport.send({ type: 'request', id, method, params });
                };

                return {
                    next(): Promise<IteratorResult<T>> {
                        ensureStarted();
                        if (buffer.length > 0) {
                            return Promise.resolve({ value: buffer.shift()!, done: false });
                        }
                        if (ended) {
                            return endError
                                ? Promise.reject(endError)
                                : Promise.resolve({ value: undefined as unknown as T, done: true });
                        }
                        return new Promise((resolve, reject) => waiters.push({ resolve, reject }));
                    },
                    return(): Promise<IteratorResult<T>> {
                        cancelAtServer();
                        end(null);
                        return Promise.resolve({ value: undefined as unknown as T, done: true });
                    },
                    throw(err: unknown): Promise<IteratorResult<T>> {
                        cancelAtServer();
                        end(err instanceof Error ? err : new Error(String(err)));
                        return Promise.reject(err);
                    },
                };
            },
        };
    }
}

