// Code generated by aprot. DO NOT EDIT.
// Handler: ProtectedHandlers

import { ApiClient } from './client';
import type { RequestOptions, PushHandler } from './client';

export interface DirectMessageEvent {
    from_user_id: string;
    from_user: string;
    message: string;
}

export interface GetProfileResponse {
    user_id: string;
    username: string;
}

export interface SendMessageResponse {
    sent: boolean;
}

export function getProfile(client: ApiClient, options?: RequestOptions): Promise<GetProfileResponse> {
    return client.request<GetProfileResponse>('ProtectedHandlers.GetProfile', [], options);
}

export function subscribeGetProfile(client: ApiClient, callback: (data: GetProfileResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<GetProfileResponse>('ProtectedHandlers.GetProfile', [], callback, onError);
}

export function sendMessage(client: ApiClient, toUserID: string, message: string, options?: RequestOptions): Promise<SendMessageResponse> {
    return client.request<SendMessageResponse>('ProtectedHandlers.SendMessage', [toUserID, message], options);
}

export function subscribeSendMessage(client: ApiClient, toUserID: string, message: string, callback: (data: SendMessageResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<SendMessageResponse>('ProtectedHandlers.SendMessage', [toUserID, message], callback, onError);
}

export function onDirectMessageEvent(client: ApiClient, handler: PushHandler<DirectMessageEvent>): () => void {
    return client.onPush<DirectMessageEvent>('DirectMessageEvent', handler);
}

