// Code generated by aprot. DO NOT EDIT.
// Handler: PublicHandlers

import { ApiClient } from './client';
import type { RequestOptions, PushHandler } from './client';

export const TaskStatus = {
    Created: "created",
    Running: "running",
    Completed: "completed",
    Failed: "failed",
} as const;
export type TaskStatusType = typeof TaskStatus[keyof typeof TaskStatus];

export interface CreateUserResponse {
    id: string;
    name: string;
    email: string;
}

export interface GetTaskResponse {
    id: string;
    name: string;
    status: TaskStatusType;
}

export interface GetUserResponse {
    id: string;
    name: string;
    email: string;
}

export interface ListUsersResponse {
    users: User[];
}

export interface LoginResponse {
    token: string;
    user_id: string;
    username: string;
}

export interface ProcessBatchResponse {
    processed: number;
    results: string[];
}

export interface ProcessWithSubTasksResponse {
    completed: number;
}

export interface SystemNotificationEvent {
    message: string;
    level: string;
}

export interface User {
    id: string;
    name: string;
    email: string;
}

export interface UserCreatedEvent {
    id: string;
    name: string;
    email: string;
}

export interface UserUpdatedEvent {
    id: string;
    name: string;
    email: string;
}


export function createUser(client: ApiClient, name: string, email: string, options?: RequestOptions): Promise<CreateUserResponse> {
    return client.request<CreateUserResponse>('PublicHandlers.CreateUser', [name, email], options);
}

export function subscribeCreateUser(client: ApiClient, name: string, email: string, callback: (data: CreateUserResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<CreateUserResponse>('PublicHandlers.CreateUser', [name, email], callback, onError);
}


export function getTask(client: ApiClient, id: string, options?: RequestOptions): Promise<GetTaskResponse> {
    return client.request<GetTaskResponse>('PublicHandlers.GetTask', [id], options);
}

export function subscribeGetTask(client: ApiClient, id: string, callback: (data: GetTaskResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<GetTaskResponse>('PublicHandlers.GetTask', [id], callback, onError);
}


export function getUser(client: ApiClient, id: string, options?: RequestOptions): Promise<GetUserResponse> {
    return client.request<GetUserResponse>('PublicHandlers.GetUser', [id], options);
}

export function subscribeGetUser(client: ApiClient, id: string, callback: (data: GetUserResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<GetUserResponse>('PublicHandlers.GetUser', [id], callback, onError);
}


export function listUsers(client: ApiClient, options?: RequestOptions): Promise<ListUsersResponse> {
    return client.request<ListUsersResponse>('PublicHandlers.ListUsers', [], options);
}

export function subscribeListUsers(client: ApiClient, callback: (data: ListUsersResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<ListUsersResponse>('PublicHandlers.ListUsers', [], callback, onError);
}


export function login(client: ApiClient, username: string, password: string, options?: RequestOptions): Promise<LoginResponse> {
    return client.request<LoginResponse>('PublicHandlers.Login', [username, password], options);
}

export function subscribeLogin(client: ApiClient, username: string, password: string, callback: (data: LoginResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<LoginResponse>('PublicHandlers.Login', [username, password], callback, onError);
}


export function processBatch(client: ApiClient, items: string[], delay: number, options?: RequestOptions): Promise<ProcessBatchResponse> {
    return client.request<ProcessBatchResponse>('PublicHandlers.ProcessBatch', [items, delay], options);
}

export function subscribeProcessBatch(client: ApiClient, items: string[], delay: number, callback: (data: ProcessBatchResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<ProcessBatchResponse>('PublicHandlers.ProcessBatch', [items, delay], callback, onError);
}


export function processWithSubTasks(client: ApiClient, steps: string[], delay: number, options?: RequestOptions): Promise<ProcessWithSubTasksResponse> {
    return client.request<ProcessWithSubTasksResponse>('PublicHandlers.ProcessWithSubTasks', [steps, delay], options);
}

export function subscribeProcessWithSubTasks(client: ApiClient, steps: string[], delay: number, callback: (data: ProcessWithSubTasksResponse) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<ProcessWithSubTasksResponse>('PublicHandlers.ProcessWithSubTasks', [steps, delay], callback, onError);
}


export function sendNotification(client: ApiClient, message: string, level: string, options?: RequestOptions): Promise<SystemNotificationEvent> {
    return client.request<SystemNotificationEvent>('PublicHandlers.SendNotification', [message, level], options);
}

export function subscribeSendNotification(client: ApiClient, message: string, level: string, callback: (data: SystemNotificationEvent) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<SystemNotificationEvent>('PublicHandlers.SendNotification', [message, level], callback, onError);
}


export function startSharedWork(client: ApiClient, title: string, steps: string[], delay: number, options?: RequestOptions): Promise<void> {
    return client.request<void>('PublicHandlers.StartSharedWork', [title, steps, delay], options);
}

export function subscribeStartSharedWork(client: ApiClient, title: string, steps: string[], delay: number, callback: (data: void) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<void>('PublicHandlers.StartSharedWork', [title, steps, delay], callback, onError);
}

export function onUserCreatedEvent(client: ApiClient, handler: PushHandler<UserCreatedEvent>): () => void {
    return client.onPush<UserCreatedEvent>('UserCreatedEvent', handler);
}

export function onUserUpdatedEvent(client: ApiClient, handler: PushHandler<UserUpdatedEvent>): () => void {
    return client.onPush<UserUpdatedEvent>('UserUpdatedEvent', handler);
}

export function onSystemNotificationEvent(client: ApiClient, handler: PushHandler<SystemNotificationEvent>): () => void {
    return client.onPush<SystemNotificationEvent>('SystemNotificationEvent', handler);
}

