// Code generated by aprot. DO NOT EDIT.
// Handler: StreamingHandlers

import { ApiClient } from './client';
import type { RequestOptions } from './client';

export interface StreamNumberItem {
    index: number;
    label: string;
}


export function streamFailing(client: ApiClient, options?: RequestOptions): AsyncIterable<number> {
    return client.requestStream<number>('StreamingHandlers.Failing', [], options);
}


export function streamNumbers(client: ApiClient, count: number, options?: RequestOptions): AsyncIterable<StreamNumberItem> {
    return client.requestStream<StreamNumberItem>('StreamingHandlers.Numbers', [count], options);
}


export function streamPairs(client: ApiClient, options?: RequestOptions): AsyncIterable<[string, number]> {
    return client.requestStream<[string, number]>('StreamingHandlers.Pairs', [], options);
}


export function streamPanics(client: ApiClient, options?: RequestOptions): AsyncIterable<number> {
    return client.requestStream<number>('StreamingHandlers.Panics', [], options);
}

