// Code generated by aprot. DO NOT EDIT.
// Handler: tasksHandler

import { ApiClient } from './client';
import type { RequestOptions, PushHandler } from './client';

export const TaskNodeStatus = {
    Created: "created",
    Running: "running",
    Completed: "completed",
    Failed: "failed",
} as const;
export type TaskNodeStatusType = typeof TaskNodeStatus[keyof typeof TaskNodeStatus];

export interface RequestTaskOutputEvent {
    requestId: string;
    taskId: string;
    output: string;
}

export interface RequestTaskProgressEvent {
    requestId: string;
    taskId: string;
    current: number;
    total: number;
}

export interface RequestTaskTreeEvent {
    requestId: string;
    tasks: TaskNode[];
}

export interface SharedTaskState {
    id: string;
    parentId?: string;
    title: string;
    status: TaskNodeStatusType;
    error?: string;
    current?: number;
    total?: number;
    meta?: any;
    children?: TaskNode[];
    isOwner: boolean;
}

export interface TaskNode {
    id: string;
    title: string;
    status: TaskNodeStatusType;
    error?: string;
    current?: number;
    total?: number;
    meta?: any;
    children?: TaskNode[];
}

export interface TaskStateEvent {
    tasks: SharedTaskState[];
}

export interface TaskUpdateEvent {
    taskId: string;
    output?: string;
    current?: number;
    total?: number;
}


export function cancelTask(client: ApiClient, taskId: string, options?: RequestOptions): Promise<void> {
    return client.request<void>('tasksHandler.CancelTask', [taskId], options);
}

export function subscribeCancelTask(client: ApiClient, taskId: string, callback: (data: void) => void, onError?: (error: Error) => void): () => void {
    return client.subscribe<void>('tasksHandler.CancelTask', [taskId], callback, onError);
}

export function onTaskStateEvent(client: ApiClient, handler: PushHandler<TaskStateEvent>): () => void {
    return client.onPush<TaskStateEvent>('TaskStateEvent', handler);
}

export function onTaskUpdateEvent(client: ApiClient, handler: PushHandler<TaskUpdateEvent>): () => void {
    return client.onPush<TaskUpdateEvent>('TaskUpdateEvent', handler);
}

export function onRequestTaskTreeEvent(client: ApiClient, handler: PushHandler<RequestTaskTreeEvent>): () => void {
    return client.onPush<RequestTaskTreeEvent>('RequestTaskTreeEvent', handler);
}

export function onRequestTaskOutputEvent(client: ApiClient, handler: PushHandler<RequestTaskOutputEvent>): () => void {
    return client.onPush<RequestTaskOutputEvent>('RequestTaskOutputEvent', handler);
}

export function onRequestTaskProgressEvent(client: ApiClient, handler: PushHandler<RequestTaskProgressEvent>): () => void {
    return client.onPush<RequestTaskProgressEvent>('RequestTaskProgressEvent', handler);
}

