// Code generated by aprot. DO NOT EDIT.

import type { ApiClient, RequestOptions } from './client';
import type { SharedTaskState, TaskStateEvent, TaskUpdateEvent, TaskNode, RequestTaskTreeEvent, RequestTaskOutputEvent } from './tasks-handler';

export interface TaskRequestOptions extends RequestOptions {
    onTaskProgress?: (tasks: TaskNode[]) => void;
    onOutput?: (output: string, taskId?: string) => void;
}

export function taskOptions(client: ApiClient, opts: TaskRequestOptions): RequestOptions {
    const { onTaskProgress, onOutput, ...base } = opts;
    if (!onTaskProgress && !onOutput) return opts;

    const unsubs: (() => void)[] = [];
    let requestId: string | null = null;

    if (onTaskProgress) {
        unsubs.push(client.onPush<RequestTaskTreeEvent>('RequestTaskTreeEvent', (e) => {
            if (e.requestId === requestId) onTaskProgress(e.tasks);
        }));
    }
    if (onOutput) {
        unsubs.push(client.onPush<RequestTaskOutputEvent>('RequestTaskOutputEvent', (e) => {
            if (e.requestId === requestId) onOutput(e.output, e.taskId);
        }));
    }

    return {
        ...base,
        _onStart: (id: string) => { requestId = id; },
        _onSettle: () => { unsubs.forEach(fn => fn()); },
    };
}

export function cancelSharedTask(client: ApiClient, taskId: string): Promise<void> {
    return client.request<void>('tasksHandler.CancelTask', [taskId]);
}


export interface TaskMeta {
    userName?: string;
    error?: string;
}
